### ISSUE TITLE
avoid requestAnimationFrame for fetch checking

### ISSUE THREAD

**Issue by technicallyfeasible** [orgsync/react-list#10]
I just noticed that while the list is visible it consumes quite a few cpu cycles and found that this is due to the update function being called every 16ms as part of requestAnimationFrame.
This means it checks 60 times per second whether the list has to be updated which is horribly inefficient.
This should be replaced with a different method, maybe listening to window resize and scroll events on the container?

**Comment by caseywebdev** [comment]
We could switch to resize/scroll events, but 2 issues/conditions come to mind:

1. On iOS, the scroll event only fires when scrolling stops. This would mean you'd need to increase the renderPageSize to prevent the end of the renderable section of the list from being visible.
2. If uniform, the size of an item cannot change after a resize or scroll event, otherwise the spacing calculations would be incorrect.

I've been playing around with a simplified version of this component lately. I'll implement the resize/scroll events in that version and see how it goes.

**Comment by technicallyfeasible** [comment]
1. I think it would not be too bad if the user can reach the end of the list and then see the "loading" content when scrolling stops. Would in some cases improve user experience because the list does not "hang" while new content is added
2. Maybe an option would be to subscribe to the requestAnimationFrame for a few seconds after the resize event has fired? It would possibly also not be an issue since the new height of items is only needed when scrolling so once the user scrolls the size would be corrected. Might introduce some issues in cases where items get smaller after the event has fired.

Looking forward to see how your test with the simplified list goes.

**Comment by technicallyfeasible** [comment]
I tested a very small optimization for the update function. Replacing this.setState(...) with this:

      // Finally, set the new state.
      var state = {
          itemHeight: itemHeight,
          columns: columns,
          index: index,
          length: length
      };
      if (!isEqualSubset(state, this.state)) {
          this.setState(state);
      }

Basically saves one React roundtrip with calling shouldComponentUpdate. It's not much but reduces processor usage by 2% for me (down from 7% to 5%).

**Comment by caseywebdev** [comment]
I've more or less rewritten the component (now two components, see the updated README).

You can play around with the test lists at http://devblog.orgsync.com/react-list/test.html. I've noticed significantly lower CPU pressure, how bout you?

This new API allows for more composition on top of it by removing a bunch of responsibility. I've created my own app-specific `FetchList` to handle some of the old behavior and it's pretty trivial.

**Comment by cmwelsh** [comment]
This is the best infinite scroll component I've used so far - simple, good performance, works out-of-the-box.

However, on iOS Safari, it does not eagerly load enough surrounding off-screen elements to compensate for the delay in updating. Thus, the user is frequently presented with a white screen for many milliseconds while scrolling.

**Comment by caseywebdev** [comment]
@cmwelsh it shouldn't be hard to support the `threshold` prop for `UniformList`, I'll work on it.

**Comment by caseywebdev** [comment]
`UniformList` now supports the `threshold` property in `0.3.2`. I tested the updated http://devblog.orgsync.com/react-list/ on iOS and the default buffer of 500px seemed to work well. Adjust as necessary for your use case!

I'm going to close this issue now as `requestAnimationFrame` is no longer being used at all.

**Comment by cmwelsh** [comment]
This works perfectly and will complement *very* well with the other issue I opened. Thanks so much.

**Comment by blakeembrey** [comment]
@caseywebdev Could you share your `FetchList`? I implemented a similar thing but it was mostly based on experimentation with the API. I extended the class and hook into `updateFrame` to handle loading more items at the end of the viewport. Is that the recommended way?

**Comment by caseywebdev** [comment]
It depends on your data API. If your first request returns a total number of results, for example, you can set the list length to that total and when `itemRenderer(item, index)` is called, you can fetch the corresponding page for that index if you don't have it yet.

If you don't know the total number of items or it's a feed or something, set the item length to the number of items you have + 1, and fetch the next page when `itemRenderer` is called for that last item.
