### ISSUE TITLE
add to readme: don't use tables

### ISSUE THREAD

**Issue by barbalex** [orgsync/react-list#102]
I tried using a table. This does not seem to work.

Then I found this issue: https://github.com/orgsync/react-list/issues/39

And I solved my problem using the method @caseywebdev shows here: https://jsfiddle.net/gzw3jspk/2/

Please prevent other people from trying to use react-list with tables and add this advice to the readme.

And: Thanks A LOT for this great tool.

**Comment by caseywebdev** [comment]
Feel free to open a PR if you'd like to mention this in the FAQ section.

**Comment by tquetano-r7** [comment]
I've used this at my job to create an infinite scroll table, and yes... Actual HTML tables. Try adding any of the code and maybe I can help. Just don't write it off.

**Comment by barbalex** [comment]
well, I guess I must have mad a mistake then. Closing

**Comment by Venryx** [comment]
There's a good example of using react-list with actual table/th/tr/td elements here: https://github.com/coderiety/react-list/issues/47#issuecomment-267654182

I use the approach shown there in my project and it works great.
