### ISSUE TITLE
Question: How is data fetched, could you hook it up to Relay?

### ISSUE THREAD

**Issue by jwaldrip** [orgsync/react-list#104]
Is there a callback to fetch the data, I.E. could we implement our own logic, such as using Relay.js?

**Comment by caseywebdev** [comment]
There isn't a specific callback to fetch data because this is a low-level component that makes no assumptions of your data. You can leverage the `renderItem` method to know what section of the list is attempting to be rendered and act accordingly. See similar issues about data fetching.
