### ISSUE TITLE
Support scroll debounce

### ISSUE THREAD

**Issue by cmwelsh** [orgsync/react-list#11]
When scrolling, the scroll event is fired too many times per second and blocks the UI thread.

I noticed this in Chrome by rendering a UniformList inside a Bootstrap modal dialog. For some reason, scrolling worked normally when scrolling the `window` object, but when scrolling an `overflow` element, the scroll was choppy, and momentum scrolling was acting choppy.

I fixed this by modifying the following line as so:

        this.scrollParent.addEventListener('scroll', require('lodash').debounce(this.updateFrame, 100));

**Comment by cmwelsh** [comment]
I ended up using `_.throttle` instead, but I think you get the gist of it. Too many scroll events causes too much work and blocks UI.

https://lodash.com/docs#throttle

**Comment by cmwelsh** [comment]
This could provide some performance, but in the end my issue persisted. :(

**Comment by cmwelsh** [comment]
For reference, my project has an 80,000px tall UniformList on `window` and a Bootstrap modal `overflow` scroll) with an 80,000px tall UniformList. These conditions cause sporadic slowdown when scrolling the modal.

**Comment by caseywebdev** [comment]
React has its own render batching strategy that should make throttling updates unnecessary. It's odd that the `window` performance was slower than the `overflow`. You can see on the demo page that the `overflow` example is 2.9 million px tall and in my tests it performs better than the window. If this is for iOS, are you using `-webkit-overflow-scrolling: touch`?

**Comment by cmwelsh** [comment]
Well... I'm stacking two UniformList components on top of each other (one `window`, one `overflow`) and the issue only happens when both are rendered at the same time.

If I have just the `overflow` modal open, performance is good.

If I have the `overflow` modal open and also another UniformList rendered underneath using `window` scroll events, then it's quite choppy on Chrome 42 (Mac OS X).

If I can get a public test URL going to reproduce I'll file an issue about it.
