### ISSUE TITLE
Can't scroll to last item on 'variable' list

### ISSUE THREAD

**Issue by rhysd** [orgsync/react-list#110]
Hi, thank you for great library.  I'm using this library for my Twitter client's timeline.

Then I have a small problem on jumping to last item.  Length of tweet text is variable hence list type is specified as 'variable'.  Then, when just after launching a client, I found that scrolling to last item didn't work.

I looked into library code and found that `getSizeOf(index)` function returns `undefined` because it reached the end of the function (no return statement hence it returned `undefined`).

Is this an expected behavior? or a bug?

**Comment by caseywebdev** [comment]
`undefined` is an expected value. It means `getSizeOf` was not able to determine the size of the item at that index.

Can you provide an example of the failing case? If your elements are not only variable but *variably* variable (change size based on viewport width, for example) you might have more luck with the `simple` type as it doesn't try to cache the heights of previous items which may become invalid after a resize.

**Comment by rhysd** [comment]
Thank you for the answer.  I considered how to jump to last item, but actually it can't without putting all elements to list (it's no longer virtualized scroll...). So I understood this is an expected behavior.
No resize event occurred so 'simple' won't help, I think. (but I'll try, thanks.)

FYI, below is a sequence to reproduce (sorry for actual working source code):

1. Create `<ReactList/>` with 20 items with type = 'variable'.
2. Call `element.scrollAround(19)`
3. It doesn't scroll

**Comment by caseywebdev** [comment]
Yup without a `itemSizeGetter` or the `uniform` type, there's no way to know how far that element is down the page until it's actually rendered.
