### ISSUE TITLE
Request render of `pageSize` elements

### ISSUE THREAD

**Issue by piranha** [orgsync/react-list#111]
It would be nice to always request render by `pageSize` elements, rather than just by necessary amount to fill whatever is in `threshold` right now.

Why: I show lists of products, and I can request few of them (but not in a way 'give me next 20 products', more 'give me products by those ids'). Right now when I render 4 products in a row, I have to ask server every time I need 4 new products. I would love to request next 12 or 24 products, to reduce amount of requests to server.

**Comment by piranha** [comment]
Oh, it does something like that in `simple`... I wonder if I can force `uniform` to render `pageSize` amount of items every time.

**Comment by caseywebdev** [comment]
You can request as many products as you want, react-list is simply the view layer. The amount of data you have does not have to equal the amount of data you're displaying.
