### ISSUE TITLE
Smarter scroll height for 'variable' mode

### ISSUE THREAD

**Issue by Rob-ot** [orgsync/react-list#113]
On mobile browsers the scrolling is decoupled from the scroll event to maintain 60fps, so in `uniform` mode it's important to have the `threshold` set pretty high (400-1200 depending on the height of rows). Still, if the user scrolls very fast in `uniform` mode they will scroll faster then the content can be rendered and they'll see a blank screen until it catches up - not really a big deal.

However in `variable` mode the height of the scroll is set dynamically as you scroll so scrolling down quickly causes the scrolling to "hit a false bottom" which stops the inertial scrolling - not good. Using an `itemSizeGetter` would fix the problem but in our case the dynamic height is due to text wrapping so we don't know the height ahead of time.

So, we need a larger scroll height sooner. 

Here's my idea: add a option `minimumRowHeight` and add the minimum heights of the remaining rows (the ones with unknown heights) to the total scroll height. As you near the bottom of the scroll there is still a chance of "hitting a false bottom" but it will be much better near the top.

As an alternative, we could average the known row heights and extrapolate that to the remaining rows. This has a chance of over-estimate the scroll height but I'm not sure that's a very bad thing since it would become more accurate as you get closer to the bottom.

I'm willing to land a pull request for this if you all think it's a good idea. Thoughts and suggestions?

**Comment by shpleef** [comment]
yes yes good idea

**Comment by caseywebdev** [comment]
I think exposing an `itemSizeEstimator` function would be the most flexible. It would allow you to return a constant if you just want to set some minimum size or do an average of known elements as well.

**Comment by Rob-ot** [comment]
Here's my attempt, I still haven't wrapped my head around the codebase so I may have missed something obvious. It works wonders for scrolling in our app. https://github.com/orgsync/react-list/compare/master...Rob-ot:master

Let me know what you think.

**Comment by caseywebdev** [comment]
Is there a specific reason for the `allowEstimation` flag? Did you find a case where using the estimator function was breaking functionality?

**Comment by caseywebdev** [comment]
Let me know if this branch works for you https://github.com/orgsync/react-list/tree/item-size-estimator

**Comment by Rob-ot** [comment]
That branch works great!

I put in the `allowEstimation` flag because I was afraid of estimated values getting cached. I don't think it matters right now since the cache is thrown away very often but with #116 that may change.

Thanks for spending time on this, it's really helpful!

**Comment by caseywebdev** [comment]
That branch should only affect `uniform` lists, while this change only affects `variable` ones, so I don't believe there'll be an issue.

**Comment by Rob-ot** [comment]
Good point. As long as estimated values don't get into the cache I don't think there's any issues with this.
