### ISSUE TITLE
React list has no way to know that render row logic has been changed

### ISSUE THREAD

**Issue by petrovalex** [orgsync/react-list#115]
If the props or state has not been changed component is not updated.
Should there be some way to notify component that rendered row has been changed?

[JsFiddle](https://jsfiddle.net/rmw48ru7/1/)

**Comment by caseywebdev** [comment]
This is a side effect of using shallow equality checking to improve performance. Check out https://github.com/orgsync/react-list/issues/36 for options to force reload.
