### ISSUE TITLE
RenderItem Cannot be pure

### ISSUE THREAD

**Issue by SeeThruHead** [orgsync/react-list#120]
looks like we have to look outside of renderItem to actually get the content to render. This means that renderItem has to be a method on a class react component. Doesn't work very well if all your components are pure functional components.
```
const Card = (index, key) => (
  <div key={index} className={styles.card}>
    <OppCard layers={displayList.get(cardIds[index]).layers} actions={actions} />
  </div>
);

const List = ({ displayList, actions }) => {
  const cardIds = [...displayList].map(R.head);

  return <div className={styles.cardList} style={{ overflow: 'auto', maxHeight: '400px' }}>
    <ReactList
      itemRenderer
    {cardIds.map((_, index) => (
    ))}
  </div>;
};
```

I'm trying to do this but can't find a nice way.

**Comment by tnrich** [comment]
@SeeThruHead your code looks slightly malformed:
```
<ReactList
      itemRenderer
    {cardIds.map((_, index) => (
    ))}
^^^^^^^^^^^^^^^^
```
Is this what you meant to post?

**Comment by SeeThruHead** [comment]
My question was more along the lines of, can itemRenderer be passed the item to be rendered in addition to it's index?

itemRenderer: (Item, index, key)

you could then write your item renderer as a pure component that doesn't need access to this.props or need to be connected (in redux terms) to the state in order to pull the entity. It's a minor issue imo, but would have been nice at the time.

**Comment by caseywebdev** [comment]
I don't see this issue? Something like this works fine without class methods.

```js
const renderCard = (card, key) => <div key={key}>{cards[index]}</div>;

const List = ({cards}) =>
  <ReactList
    itemRenderer={(index, key) => renderCard(cards[index], key)}
    length={cards.length}
  />;
```

**Comment by SeeThruHead** [comment]
yeah that's a fine solution. I'm still of the opinion that it would be nice to provide reactList with an items prop and have the appropriate item passed to item renderer by reactList but this is a suitable workaround. thanks
