### ISSUE TITLE
React List is accessing findDOMNode within its render()

### ISSUE THREAD

**Issue by tnrich** [orgsync/react-list#121]
Here is an image of the react warning I'm seeing:

![image](https://cloud.githubusercontent.com/assets/2730609/16854052/2b748fb2-49c4-11e6-83aa-0acbe4740ecd.png)

I don't think I'm using react-list incorrectly. Have you all every seen this error (I think it only shows up in the latest version of react)? Any help making it go away would be appreciated. 

Thanks!

**Comment by theopolisme** [comment]
A user just triggered around 1.2k Invariant Violation errors based upon what may be the same issue (or at least related -- specifically, the edge case of the findDOMNode not being called until after the component is unmounted... somehow?). Here is one of the stack traces: https://app.getsentry.com/share/issue/39333338362e313532323638303237/

This hasn't ever happened before, so I'm a bit confused as to what's going on... any insights? We're on React 15.3.1.
