### ISSUE TITLE
Crashing browser

### ISSUE THREAD

**Issue by SeeThruHead** [orgsync/react-list#122]
As soon as i remove overflow: scroll and maxHeight from something directly surrounding the list the page crashing due to what i assume is some infinite loop.

I am trying to use react-list based on the window scroll, with a fixed header.

**Comment by caseywebdev** [comment]
Please provide an example.

**Comment by SeeThruHead** [comment]
couldn't repro in a clean env, then somehow the issue went away. (I believe removing all overflow: auto from any element helped)
