### ISSUE TITLE
Unknown prop keys

### ISSUE THREAD

**Issue by cocacrave** [orgsync/react-list#123]
After updating to React 15.2.1 from React 15.1.0, I'm getting this error Unknown Prop 'keys' warning in console.

Warning: Unknown prop `keys` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div
    in div (created by ReactList)
    in div (created by ReactList)
    in ReactList (created by BuildMap)
    in div (created by BuildMap)
    in div (created by BuildMap)
    in BuildMap (created by BuildWrapper)
    in div (created by BuildWrapper)
    in BuildWrapper (created by Dashboard)
    in div (created by Dashboard)
    in div (created by Dashboard)
    in div (created by Dashboard)
    in div (created by Dashboard)
    in Dashboard (created by RouterContext)
    in div (created by Dashboard)
    in Dashboard (created by Container(Dashboard))
    ....

**Comment by caseywebdev** [comment]
`react-list` doesn't use a `keys` prop anywhere, so this is likely an issue with either your `itemRenderer` or `itemsRenderer` function.

**Comment by cocacrave** [comment]
I'm sorry, this was my mistake. I fixed it now
