### ISSUE TITLE
Could we make `className` a prop that gets passed down?

### ISSUE THREAD

**Issue by elsigh** [orgsync/react-list#124]
Happy to send a PR but I noticed that 
`<ReactList className="foo" ...` doesn't pass my className down the div, so I'm using a direct descendant selector in CSS to target it. Would rather be able to pass `className` down unless you specifically didn't want that.

**Comment by kiresuah** [comment]
you can pass a function to place your own div with a classusing the itemsRenderer property:

```
<ReactList
   itemRenderer={this.renderItem}
   itemsRenderer={(items, ref) => <div className="foo" ref={ref}>{items}</div>}
   length={history.length}
   type="uniform"
   axis="x"
   useStaticSize
/>
```

**Comment by elsigh** [comment]
Fair enough. =)

**Comment by NeXTs** [comment]
itemsRendered should be documented a bit better :)
just refer from docs to this example and life of some developers would be easier

I had to search example in issues to get idea how to use it, pretty sure others did same

**Comment by elsigh** [comment]
I just searched for it again myself, lol.
