### ISSUE TITLE
Compared to React-Virtualized?

### ISSUE THREAD

**Issue by oyeanuj** [orgsync/react-list#126]
Hi @caseywebdev! The library looks great, thanks for open sourcing it! The other major library in this case seems to be react-virtualized. Apart from support for variable row heights, I am curious to understand architecturally how does react-list differ from react-virtualized and their pros/cons?

I assume a comparison of some sort will also be helpful to others who come across this library in the future!

Thank you!

**Comment by caseywebdev** [comment]
I haven't used react-virtualized so I can't speak to their similarities/differences. We built this component to handle the various list use cases we have in our product and it was important that a very large number of uniformly-sized items are supported but also variably sized items for long news feeds and such. For choosing any library you're not sure about, I'd recommend trying each out and using whichever better suits your use case.
