### ISSUE TITLE
please enable event handler as 'passive'

### ISSUE THREAD

**Issue by crisys11** [orgsync/react-list#129]
please see https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

Sometimes in chrome throw this alert, because mouse event handlers not are passive this cause in some scenarios jank

Handling of 'mousewheel' input event was delayed for 239 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.

**Comment by caseywebdev** [comment]
Yikes! That event handler is there as a hack anyway. You're saying I need to hack the hack to get Chrome working correctly? That's unfortunate...

Does that event handler even need to be there still?

**Comment by cocacrave** [comment]
Yep, getting the same thing too.

**Comment by caseywebdev** [comment]
Fixed in `0.7.21`
