### ISSUE TITLE
Uniform List fails with flexbox

### ISSUE THREAD

**Issue by blakeembrey** [orgsync/react-list#13]
Continuing from #8.

I'm using flexbox in my application (and to render the list), but I can't use the uniform list with it because it's container is block by default. This limits the type that rendered children can be and what they will inherit (for example, I use `justify-content: space-between` for even spacing). On top of that, if I use flexbox by default so it breaks the block height (without `flex: 1` being set). This result in only the first item ever being rendered since the container is height of zero. Without the container being flex, the children don't render properly either (they appear block instead of beside each other evenly spaced).

The only proper solution (I can think of) is to specify some sort of custom container, class or style pass through. 

Here's an [example](https://jsfiddle.net/xzprmsm7/1/).

Edit: Updated fiddle to https://jsfiddle.net/xzprmsm7/1/, apparently I don't do this often.

**Comment by caseywebdev** [comment]
Check this out: https://jsfiddle.net/xzprmsm7/3/

It looks like you might want to use the `itemsRenderer` prop to render the flexbox container.

**Comment by blakeembrey** [comment]
Right, I can do that. Either way, it seems like I'll be working around the issues, since all elements are set to `display: flex` by default for me. I'll review it and see what I can work around, but I'm guessing that'll I'll have to target it using `.x > div > div` selectors for now.

**Comment by caseywebdev** [comment]
I'm going to close this issue for now then.

**Comment by Gianarci** [comment]
This is not working. I've tried both the examples in jsfiddle, but I obtain 'ReactList failed to reach a stable state'. How to properly render multiple items on a row?
