### ISSUE TITLE
Ideas to implement this with a fixed header

### ISSUE THREAD

**Issue by brene** [orgsync/react-list#137]
I want to ask a question. Can I use this like a table, where the first row would be fixed in vertical space but would scroll along horizontally? Is this possible with react-list?

**Comment by caseywebdev** [comment]
We do this with one of our products at OrgSync, but unfortunately I can't provide a demo. The basic idea is to put the header div and list div in a wrapper div with `overflow-x: auto`, then wrap the list div in an `overflow-y: auto`. This way they both move horizontally the same but only the list moves vertically. Good luck!
