### ISSUE TITLE
Infinitive loop - stucks or stops

### ISSUE THREAD

**Issue by pionl** [orgsync/react-list#142]
I'm using the list to render a list of items with uniform settings. The div uses h3 and a div with bootstrap rows. If I remove them, the list works prefectly. The infinite loop mostly happends when the last item should be rendered (16 items, loops go from 6-15, then lists receives update and renders again with new index range 5-15, then the update is triggered again and goes from 6-15).

react-list.js:285 
Uncaught TypeError: Cannot read property 'children' of null
getItemSizeAndItemsPerRow 
@ react-list.js:285
updateUniformFrame 
@ react-list.js:403
updateFrame 
@ react-list.js:318
- using uniform (sizes are: 129, 90, 90, 90, 90, 129, 90, 65, 129, etc)
- when using variable, works ok (first the scrollbar is bigger, than smaller - is ok), but if i added new item and the source has changed (90, 129, 90, 90, 129, 129), it triggered the infin. loop at first render.
- simple works ok.

Any advice are welcomed, love the your library.
Thanks,
Martin.

**Comment by degroote22** [comment]
You're rendering a variable-sized lista. Trying to use uniform will crash the list. Is this the case? Could you post more details?

**Comment by STRML** [comment]
Crashes no longer occur as of `0.8.3` so this should be safe to close. The first reply above should address the underlying issue.

**Comment by caseywebdev** [comment]
Sounds good
