### ISSUE TITLE
Don't render single item while not in viewport?

### ISSUE THREAD

**Issue by NeXTs** [orgsync/react-list#143]
Hey

It's more like topic for discussion of feature request than a question.
Since this lib observes scroll position and aware if specific item are in viewport or not - it may be handle for lazy-loading of whole single-container cases. That's what I mean

On my website I have a footer container with statistics. By design that statistics container has quite big image on background and a lot of svg icons inside which in total cost something in terms of bandwidth too.

Since I've already use react-list on this project for lists I was expected to use react-list for lazy-loading purposes of footer too. I was hoping that by wrapping footer in `<ReactList />` and settings `length={1}` it would observe scroll position and render footer only if it's in viewport. Whereby page will works faster because of less amount of DOM-nodes and faster page loading by reducing requests to images/svg which are not in viewport (little amount of people actually scrolling down to footer so loading of everything on start is redundant for those who don't).

But it didn't. Seems to be react-list renders first bunch of items in any type (simple/variable/uniform) or something, despite of any threshold I set. Footer and statistics are in DOM even if it's 5000px down from page top.

Of course there may be other libs that were created exactly for this case but I don't want to increase bundle.js size by one more lib, it's already bigger than I'd like it to be.

How do you think, it is possible to implement such behaviour with current options?

**Comment by ashokkumarsand** [comment]
I don't think so, But there is new things can be discovered and new API can be implemented

**Comment by caseywebdev** [comment]
This has been implemented in `0.8.4`. This is not possible with `uniform` lists because the size of the list is derived from the first element, but it should work with `simple` and `variable` lists.
