### ISSUE TITLE
Look for scrollable parent from the single item element

### ISSUE THREAD

**Issue by albertogasparin** [orgsync/react-list#147]
It looks like defining the items renderer as scrollable does not work:

```js
// ...
renderItems(children, ref) {
  return (
    <ul ref={ref} style={{ overflow: 'scroll' }}>{children}</ul>
  );
}
renderItem(i) {
  return (<li>{i}</li>);
}
render() {
  return (
    <ReactList
      itemsRenderer={this.renderItems}
      itemRenderer={this.renderItem}
      length={10}
    />
  );
}
```

Looks like the plugin starts checking scrollable parents from the `ReactList` component. I think it should be better to start from the single item, as the `itemsRenderer` function could return a scrollable element.

**Comment by caseywebdev** [comment]
The element returned by the `itemsRenderer` function must not be scrollable. Customize your scrollable element as a wrapper around `<ReactList />`.

**Comment by albertogasparin** [comment]
Ok, would you mind adding a note on `itemsRenderer` (or under FAQ) so people know about this limitation? Thanks
