### ISSUE TITLE
initialIndex doesn't work if index hasnt already been loaded

### ISSUE THREAD

**Issue by McPo** [orgsync/react-list#148]
Im aware that scrollTo and scrollAround both require the element to have been previously loaded. However Im observing the same behaviour with initialIndex, considering the documentation doesn't explicitly call this out, I would have assumed that initialIndex would work for any index.

Im attempting to get behaviour similar to https://github.com/orgsync/react-list/issues/50, and would've thought that Id be able to set the initial Index to the last index. Instead it appears to move to the end of the 'page'.

ie List has 1000 items, initialIndex=999, but actually only scrolls to ~10.

Is this the intended behaviour?

Thanks,
Emmet

**Comment by McPo** [comment]
It appears the behaviour I was seeing it tied to using simple mode. When I changed it to uniform, I had better success however when I scrolled up, it then jump from 5000 to 1500.

**Comment by caseywebdev** [comment]
With the simple list it's impossible to jump to anything that hasn't been rendered as there's no way to know how far down it is. The reason it's possible with uniform or variable with itemSizeGetter is that we can calculate the distance to scroll before actually rendering anything.
