### ISSUE TITLE
Infinite scroll in both directions

### ISSUE THREAD

**Issue by babsonmatt** [orgsync/react-list#15]
Potential to add this?

**Comment by caseywebdev** [comment]
Maybe, what's your use case?

**Comment by babsonmatt** [comment]
Use case would be something along the lines of being able to provide an offset in the list, and being able to scroll up to previous items.

**Comment by caseywebdev** [comment]
Here's an example of the new `initialIndex` prop: https://jsfiddle.net/xzprmsm7/4/

**Comment by babsonmatt** [comment]
Awesome.

**Comment by jordansexton** [comment]
@babsonmatt It's not logically a uniform list if the item heights are variable. It seems to me that `List` could have an `itemHeight` property as well, which could be some combination of:

- a number
- an array of numbers
- a getter function that is called with the item index and is expected to return a number

An array of numbers on its own is limited and against the spirit of `react-list` not taking an `items` array but just a length property for which it will calculate indices.

I imagine what you're trying to achieve is the variable height behavior of `List` with the DOM element culling of `UniformList`. This isn't possible to do while maintaining correct scroll position unless the heights are known in advance, and it would be wasteful, and for many use cases impossible, to determine the heights of items which haven't been displayed, and maybe haven't even been loaded, and might contain additional unloaded content like images for which the height can't necessarily be known upfront.

While `react-infinite` handles this by accepting an array of heights, I think a getter function is much more flexible and compatible with the design of `react-list`. Regardless, it would be quite confusing if UniformList were not uniform. I imagine a better solution is to abstract the behavior you want (DOM element removal/reuse) away from `UniformList`.

**Comment by asutherland** [comment]
For the variable height stuff, you might want to check out https://github.com/orgsync/react-list/issues/21 which I just filed with a prototype.  It's only appropriate where the UI design is sufficiently constrained that heights can be known without performing layout.
