### ISSUE TITLE
PureRenderMixin, don't depend on React.addons

### ISSUE THREAD

**Issue by steffenmllr** [orgsync/react-list#16]
I think you can get rid of the `React.addons` dependency and just include the `ReactComponentWithPureRenderMixin` via:

```js
import PureRenderMixin from 'react/lib/ReactComponentWithPureRenderMixin';
```

Would send a PR but I'm not entirely clear on how your build system work :)

**Comment by caseywebdev** [comment]
That would require consumers to use Browserify, which we don't want. Fortunately this won't be an issue at all as I'm removing the dependency on React.addons in an upcoming release.

**Comment by steffenmllr** [comment]
Ah ok, nice! Looking forward to the next release :)

**Comment by caseywebdev** [comment]
This is the case now. `0.5.4` does not require React with add-ons.
