### ISSUE TITLE
Broken on SSR

### ISSUE THREAD

**Issue by mfollett** [orgsync/react-list#173]
A recent change caused `uniform` type react-list components to render only a single element when being generated on the server in universal React applications. To solve this I would like to add a new field, `initialPageSize` that defines the number of items that should be rendered on the server with `uniform` type lists. Would that be alright?

**Comment by caseywebdev** [comment]
I've encountered multiple use cases like this, does #174 work for your case? Setting `minSize` should ensure you don't end up with an initial render of just 1 for uniform lists, and also allows other lists to have some minimum amount of items while maintaining a lower `pageSize`.

**Comment by mfollett** [comment]
Yeah, that looks good.

**Comment by mfollett** [comment]
What's the timeline for a release with that change?

**Comment by caseywebdev** [comment]
How bout 90 seconds

**Comment by caseywebdev** [comment]
Released in `0.8.6`

**Comment by mfollett** [comment]
Ha wow, awesome, thanks a bunch for such a fast turn around. Also, thanks for `react-list`, it is pretty slick.
