### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by psamim** [orgsync/react-list#186]
Hi,

I get `Cannot read property 'length' of undefined` at https://github.com/orgsync/react-list/blob/master/react-list.es6#L221 .

It seems that `items` has `props.children` but not `children`, so `items.children` is undefined. I do not know what is causing the issue, has React API changed?

Thanks,
Samim

**Comment by caseywebdev** [comment]
The last update removed the `react-dom` dependency in favor of `ref={c => this.el = c}` syntax. Seems like the `ref` isn't being set correctly for your implementation. Please paste an example of this failing case.

**Comment by darkowic** [comment]
This is breaking change :confused: Should not be released in bugifx release...

**Comment by caseywebdev** [comment]
The `ref` needs to be applied to a DOM element. I'm assuming it's being applied to another custom component and that's the issue.

**Comment by darkowic** [comment]
Ok in my case it was a problem with styled components probably. Until you used react dom `findDOMNode` to get the node everything was fine.

This is how my structure looks like https://www.webpackbin.com/bins/-KuUvAHMYeP1rL7PsiN7

So the ref is not passed through components when I'm overriding. I have to ask someone for help in this case.

**Comment by caseywebdev** [comment]
See https://www.webpackbin.com/bins/-KuV8RXQYliLC0BcSDrU

Unfortunately React will not exposed `ref` in `props`, so if you're doing something like this you need to rename ref like I have with `myRef`.
