### ISSUE TITLE
Loading data asynchronously causing rendering issues with uniform list

### ISSUE THREAD

**Issue by blakeembrey** [orgsync/react-list#20]
The initial load, height is 0. Once I scroll, it picks up the child height (incorrectly though, because the child height is being constrained by the height of 0 - yes, I can explicitly set element heights to fix this) and renders normally.

![image](https://cloud.githubusercontent.com/assets/1088987/7553060/682f2620-f6b3-11e4-99a4-1e78f22543e7.png)

**Comment by caseywebdev** [comment]
I've always given images explicit dimensions to avoid this problem. Do you have a suggestion on how to handle dynamic height changes implicitly? The previous solution was `requestAnimationFrame`, but we decided that was too heavy :wink:

**Comment by blakeembrey** [comment]
@caseywebdev Actually, it's not fixed by setting explicit heights. It seems to be caused by the initial render which sets the parent container height to zero (there's no items). However, when it updates it isn't recalculating any heights so it decides it can still only hold the first item. Once you scroll, all the items appear. I'll debug it more once I have a chance.

**Comment by blakeembrey** [comment]
This seems to be working fine with the latest API change. However, I'm still having an issue with the height calculation of the whole list, but I can log it later.

**Comment by blakeembrey** [comment]
Figured out the height calculation, it wasn't including margins. Switched to using padding and no more issue. Not sure if you want to attempt fixing it since it could be tricky (margins normally collapse, but don't in other situations).

**Comment by caseywebdev** [comment]
Margins are tricky for that reason . I'd generally advocate wrapping in a container element with padding when it's necessary like you did.
