### ISSUE TITLE
Add a list variant supporting variable-height items for use with an async data-store that knows item highs a priori

### ISSUE THREAD

**Issue by asutherland** [orgsync/react-list#21]
First things first: working prototype: https://github.com/asutherland/react-list/tree/quantized-variable-list
With demo page via gh-pages: http://asutherland.github.io/react-list/quantized.html
And many thanks for all the great work on react-list!

## Context / Background ##
I am working on an experimental react.js-based desktop-targeted email app based on the mobile-targeted Firefox OS email app as part of an overhaul of the back-end to support conversation-centric operation (like gmail) versus message-centric operation (standard IMAP).

My requirements are:
* Asynchronous data-store control flow.  The email back-end runs in a DOM Worker and it's an offline client intended to run on devices without gobs of memory, so the state lives in IndexedDB.
* True virtual list behaviour with random-access seeking where displaying items M..N should not require loading/displaying all of 0..M-1 as well.

Fancy scope creep:
* It's cool to have variable-height display of a conversation based on how many new/unread messages there are, or how important it is, etc.  See https://clicky.visophyte.org/files/screenshots/20150507-153614.png for a shoddy example from a few days ago.
* It's nice to be able to both buffer for anticipated scrolling and know what is actually visible so we can prioritize actions like fetching message snippets for the visible messages before the not-yet-visible messages.

Simplifications:
* Many UIs are based on everything being a fixed multiple of a grid/similar.  In the example of the conversations case, the idea is there's basically a conversation overview (with a height multiple of 1), and up to 3 tidbits from unread messages (each with a height multiple of 1).
* For a uniform height implementation we already need to maintain a concise index/view of the conversations.  It's relatively cheap to store the height multiple information as well.

## Why react-list ##
react-list has continually been the best option in my various react.js experiments over the past several months.  I really enjoy how clean the code is and the effort that's gone into keeping it clean.  I figured I'd start from react-list as a base and see if it makes sense to contribute something that meets my needs.  I am okay if this is too crazy / different.

## General Implementation ##
In my branch I added some docs to the README.md at https://github.com/asutherland/react-list/tree/quantized-variable-list#reactlistquantizedheightlist that should help shed some light.

Because of the async control flow, how I've already implemented my data model/backend, and the idiom I settled on for getting the older 0.3.x react-list to re-render as my data updates and having my components be smart with shouldComponentUpdate, I settled on:
* The quantized height list widget is more stateless than its relatives.  Its owner/user pushes in the stuff to display as props.
* The list widget issues seek() calls (a prop function passed in by the owner/user) to trigger the data-model to fetch more data and eventually update the props.
* The only real state the widget has is avoiding issuing redundant seek() calls by requiring the user to have scrolled some minimum distance before a new seek call is issued.  I store this directly as _lastScroll on the component instance rather than using setState.  This feels wrong (and may also technically be wrong :), but I was trying to avoid needing a custom shouldComponentUpdate mechanism that would ignore that state property since we don't actually want to trigger any re-rendering until the new data comes in via props.  The custom shouldComponentUpdate is still probably right.

## Questions ##

* Is this something that seems appropriate to live in react-list in any form?
* Is this implementation approach viable?  Does a better way to do this jump out?
* What's a less horrible name than QuantizedHeightList? :wink:

**Comment by caseywebdev** [comment]
Check out the new `0.5.0` release with better variable height support. Also, check out the 3rd example on http://devblog.orgsync.com/react-list/ that demonstrates the `itemHeightGetter` prop. My goal was to keep the API as simple as possible. Once it gets too complicated it's difficult to build anything on top of it.

For your email case, it seems you could always return the correct height given an email index because you'd know how many preview lines you're showing. I'm going to close this issue for now since the support is now in master.

**Comment by asutherland** [comment]
Awesome variable-height update support.

Unfortunately I don't think the async data-flow where the data lives in a separate DOM Worker entirely lines up for my conversation use case.  react-list assumes the getters can synchronously provide information.  (A reasonable simplifying requirement!)  I could deal with this by having a synthetic spacer element, but this seems to be fighting the work react-list is doing internally.

So I figure I'll see what happens if I whittle down QuantizedHeightList to a standalone implementation that assumes my seek flow using props.  Assuming it's small enough, perhaps it makes sense for me to create a react-async-virtual-list thing for consumers with similar use-cases.  And then I'd continue to use react-list for things like account lists and folder lists where all of the information is synchronously available and there's no need for the async flow.

**Comment by caseywebdev** [comment]
Can't your `itemHeightGetter` return some height for when it's loading and then another height when you have the information necessary?

**Comment by asutherland** [comment]
Sort of?  In 0.5.0 with type=variable the coordinate space is item indices.  updateVariableFrame synchronously figures out what item indices are visible by what the itemHeightGetter returns at that instant.  Calling itemHeightGetter is no indication that an item wants to be rendered, just that it's visible or above the visible area (both updateVaraibleFrame and getSpaceBefore) do this.  So any lies I tell really complicate things.  The only viable option is for my Worker to send height information on all the items from 0 until react-list stops asking for things that aren't known in the page.

This doesn't sound too horrible at first glance since users normally scroll downwards, but gets worse when dealing with the fact that a potentially huge number of changes may occur in that list in the "space before" impacting the coordinate space.  When the list widget's understanding of this is just a coordinate space offset it's told about, it nicely simplifies things.  It also allows the back-end to be aware of a stable "focus" item/position so that if changes happen in the "space before" that we can provide visual persistence for the user while still updating scroll positions to be accurate by tracking the concept of coordinate space drift between the actual true list and what the user currently sees.  When the user stops scrolling, we can synchronously update scrollTop and our display transforms in a single pass to reset the drift to 0.

Also there's some O(n) scaling issues.  While react-list can obviously optimize things to do more caching/etc. at the cost of needing to handle cache invalidation, it's hard to compete with the canonical data model that owns the changes and has access to persistent data-storage like IndexedDB.
