### ISSUE TITLE
Question: Implementing 'FetchList'

### ISSUE THREAD

**Issue by babsonmatt** [orgsync/react-list#24]
Any suggestions for the best way to load new items from remote while scrolling?  I was planning to request new items within the itemRenderer method, but I'm not sure that works, as it fires once for every index trying to be rendered and I can't setState some sort of  { loading: true } within the render process to limit repetitive requests for new pages of items while processing.

Any ideas?

Thanks a lot.

**Comment by caseywebdev** [comment]
I haven't tested this, but this is the basic idea

```js
import _ from 'underscore';
import myDataFetcher from 'my-data-fetcher';
import React from 'react';

class FetchList extends React.Component {
  pending = [];
  isLoading = false;
  
  request(index) {
    this.pending.push(index);
    this.fetch();
  }
  
  fetch() {
    if (this.isLoading || !this.pending.length) return;
    const from = _.first(this.pending);
    this.isLoading = true;
    myDataFetcher({from}, _.partial(this.handleFetch, from));
  }
  
  handleFetch(from, results) {
    this.isLoading = false;
    this.props.onItemsUpdate(
      _.reduce(results, (items, item, index) => {
        index += from;
        items[index] = item;
        this.pending = _.without(this.pending, index);
        return items;
      }, _.clone(this.props.items))
    );
    this.fetch();
  }
  
  renderItem(index, key) {
    if (!this.props.items[index]) this.request(index);
    return this.props.itemRenderer(index, key);
  }
  
  render() {
    return <List {...this.props} />;
  }
}
```

When you get a `itemRenderer` call for an index you haven't loaded yet, you add that index to a list then try to fetch. After a fetch succeeds, remove all pending indices that were fetched in that request and try fetching again until all requested indices have been loaded. I've elected to remove `ReactList` from this process because it can vary greatly by implementation. Creating your own version of `FetchList` on top of `ReactList` shouldn't be too bad, and will almost always be app-specific.

**Comment by babsonmatt** [comment]
Thanks a lot for the example code, I actually ended up implementing something very similar... but I think I've come across a potential issue, perhaps you could offer a suggestion?  Returning null from itemRenderer when an index that isn't available is requested, ends up with ReactList flying through the remainder of the list items (which are all null).

So say you have 0-9 pre loaded, when the request for index 10 comes to itemRenderer it's going to receive null, and will then request 11, 12 ... until the max length of the list - 1.  So this ends up basically defeating the point of 'lazy loading' as all requests for all items/pages get hit at once.

Hopefully I've explained this well enough and you can shed some light on things for me, thanks again for your help + the library.

**Comment by caseywebdev** [comment]
If you use type=uniform or itemSizeGetter this isn't a problem, but without those I'll generally render a div with either empty space or a loading indicator. You should never really render an item as null, even if it isn't loaded yet, as it WILL take up some amount of space when it is loaded, and if you don't know how much beforehand give it your best estimate and things will work out fine.

**Comment by babsonmatt** [comment]
Thanks for the help!

**Comment by caseywebdev** [comment]
No problem :thumbsup:

**Comment by trungpham** [comment]
why was the old fetch prop taken away?

**Comment by caseywebdev** [comment]
The reason was to reduce the scope of this component, making it easier to compose with other components.

**Comment by geekyme** [comment]
this left me a little confused, so how do i implement remote fetching of items? I don't see any method to pass to `react-list` to fetch more items when it hits the bottom threshold.

**Comment by caseywebdev** [comment]
The basic idea is you set your `length` to the length of your loaded content `+ 1`. When `itemRenderer` is invoked with that last index, you know you've reached the bottom of the list and it's time to load more. You can treat that extra, not loaded item, as a loading indicator for a better UX.

**Comment by geekyme** [comment]
isn't item renderer supposed to be used for rendering an item? not fetching more items?

**Comment by caseywebdev** [comment]
You do render an item. When invoked it also implies you should have something there to render. I usually keep a map of indices that have been reached in the view but I haven't fetched yet, and then intelligently create a request from there based on what's visible to the user.

**Comment by geekyme** [comment]
That seems like a very common use case though. Wouldn't this be better implemented within the library core? We should pass react-list children component, then react-list should read this.props.children and once the scroll hits somewhere near the last child, fire a "loadMore" function that is supplied by this.props.loadMore. 

Just some thoughts. But otherwise the scrolling is v well done in this library.

**Comment by caseywebdev** [comment]
This component has purposefully remained agnostic as to how or when you retrieve your data. It's trivial to detect reaching the bottom of the list inside the itemRenderer handler. If you feel strongly about a higher level component for bottom-of-list fetching I'd encourage you to create a new component composed with this one.

**Comment by sms1983** [comment]
Although I understand this being "how to load agnostic" and agree with it, I suggest having at least a link to this thread on the documentation so that everyone gets examples and understand this motivation. I was a little lost about that until I got here.

**Comment by simax** [comment]
Hey caseywebdev,

I wonder if you could do me a huge favor. I'm trying to follow your code above and build a "toy" FetchList component just so I can get my head around it before I plug it into my real app but I'm clearly missing some key stuff here. 

I'm trying to produce a list of randomly sized items and when I scroll to the bottom of the list I want to fetch a batch of 10 at a time.

Now, initially I do get a list of 10 randomly sized items on the screen but when I scroll to the bottom no events fire and my itemRender method never gets called again. I suspect it could be something to do with the length property never being updated but I don't know how to proceed.

Here's my feeble attempt so far:

```
'use strict';

var React = require('react'),
  _ = require('underscore'),
  ReactList =require('react-list');

const ItemType1 = React.createClass({
  render() {
    return (<div style={{background: 'Red', height: this.props.itemHeight}}>
      <div key={this.props.key} style={{paddingTop: 50, paddingLeft: 200, color: 'White', fontSize: 40}}>
        {this.props.name}
      </div>
    </div>);
  }
});

const ItemType2 = React.createClass({
  render() {
    return (<div style={{background: 'Green', height: this.props.itemHeight}}>
      <div key={this.props.key} style={{paddingTop: 50, paddingLeft: 200, color: 'White', fontSize: 40}}>
        {this.props.name}
      </div>
    </div>);
  }
});


function getDataItems(from, dataItems) {
  let numberOfRows = 10;
  let min = 0.2;
  let max = 0.5;
  for (let i = from; i < numberOfRows; i++) {
    let h = Math.floor(1000 * Math.random() * (max - min + 1) + min);
    let name = `Item-${i.toString()}`;
    let compToRender = (i % 2) == 0
      ? <ItemType1 key={i} itemHeight={h} name={name}/>
      : <ItemType2 key={i} itemHeight={h} name={name}/>;

    dataItems.push(compToRender);
  }
}

function myDataFetcher(from, cb) {
  let dataItems = [];
  getDataItems(from, dataItems);
  console.dir(dataItems);
  return cb(dataItems);
}

const UserNewsFeeds = React.createClass({

  pending: [],
  isLoading: false,

  request(index) {
    this.pending.push(index);
    this.fetch();
  },

  fetch() {
    if (this.isLoading || !this.pending.length) return;
    const from = _.first(this.pending);
    this.isLoading = true;
    return myDataFetcher(from, _.partial(this.handleFetch, from));
  },

  handleFetch(from, results) {
    this.isLoading = false;
    this.pending = _.without(this.pending, from);
    this.props.items.push(results);
    //this.props.onItemsUpdate(
    //  _.reduce(results, (items, item, index) => {
    //    index += from;
    //    items[index] = item;
    //
    //    return items;
    //  }, _.clone(this.props.items))
    //);
    this.fetch();
  },

  renderItem(index, key) {
    if(!this.props.items[index]) this.request(index);
    return (<div>{this.props.items[index]}</div>);
  },

  render() {
    return (
      <div>
        <h1>News feeds items</h1>
        <div style={{ overflow: 'auto', maxHeight: 400 }}>
          <ReactList {...this.props} itemRenderer={this.renderItem} length={this.props.items == 0 ? 1 : this.props.items + 1}/>
        </div>
      </div>
    );
  }

});

module.exports = UserNewsFeeds;
```

I realize it's a lot to ask but I would greatly appreciate your guidance here.
