### ISSUE TITLE
how could I pass the variables to the itemRenderer method?

### ISSUE THREAD

**Issue by ripple0328** [orgsync/react-list#25]
for some reason I can not pass them like {this.state.accounts[index]}
(the ReactList was composed dynamically during the parent component be rendering, so I can not set any state while that)

is there a way to directly pass some variables into the itemRenderer method?

**Comment by ripple0328** [comment]
I just use  
```
{ displayName: 'productList',   
items:  null,
render: ...
}
```
to share variables between functions.

**Comment by codemonkeynorth** [comment]
in ES6 I do it like this.. (index & key are already passed so we need to forward them)

```javascript
itemRenderer={(index, key) => this.renderRow(index, key, arg)}

...

renderRow(index, key, arg)
{
```
