### ISSUE TITLE
anyone know how to test the scroll on a component?

### ISSUE THREAD

**Issue by ripple0328** [orgsync/react-list#26]
I want to test the actually DOM keep the page size I give and after a scroll the reactList should update with new Dom,  but I have no ideas how to do that. 

I tried this:
```
React.addons.TestUtils.Simulate.scroll(React.findDOMNode(component.refs['itemsList']),{deltaY: 200});
```
it's not working...

**Comment by caseywebdev** [comment]
Try scrolling `component.refs.itemsList..scrollParent`, which should be a reference to either `window` or the closest parent element that is `overflow: scroll` or `overflow: auto`.
