### ISSUE TITLE
Rare cases when getScroll() changes unnoticedly

### ISSUE THREAD

**Issue by CoffeeKitty** [orgsync/react-list#31]
It is possible that the return value of `getScroll()` can change without triggering any of these events:
1. window resize
2. scrollParent scroll
3. React component update

An example is: a stateful component rendered above the ReactList, which height depends on its state.

When this happens, ReactList is uninformed of the change. The `threshold` can help to some extent, but how should we handle the general case?

**Comment by caseywebdev** [comment]
You'll want to call `forceUpdate()` on the component directly in this case. After a `forceUpdate()` the component will recalculate sizes and should correct itself.
