### ISSUE TITLE
Click and drag does not scroll farther than rendered list

### ISSUE THREAD

**Issue by tquetano-r7** [orgsync/react-list#32]
So I've been playing around with your component (which is friggin awesome, btw), and the only shortcoming I've seen thus far is that the scrollbar is based on the items rendered ... if I click and drag it to the bottom, slowly more items are rendered and it goes down, but it doesn't "jump to the middle" like I would expect. Is there a specific property I need to activate for this?

I imagine it would involve something like setting the total height of the container to the height of all items, while only rendering the items needed in that "window", even if that is an estimated height. If it helps, here is a link to a jsFiddle I found that implements it: http://jsfiddle.net/vjeux/KbWJ2/9/.

**Comment by caseywebdev** [comment]
You can do this if you use the uniform type or if you use the variable type with an itemSizeGetter function. The examples need more docs, but check out the ones toward the bottom and let me know if that's what you're trying to achieve.

**Comment by tquetano-r7** [comment]
Yup, that got it working. I'm a little bummed because it broke my CSS hack for fixed table headers on table markup (positioning + translate on the extra div wrappers), but I understand the performance reasons you did those extra wrappers. Thanks!
