### ISSUE TITLE
Your take on a semi-similar effort

### ISSUE THREAD

**Issue by tnrich** [orgsync/react-list#33]
Hey there, 

I don't know how it's only now that I found your excellent package, but I thought I'd reach out and compare ideas: 
https://github.com/tnrich/react-variable-height-infinite-scroller

I made the above scroller to use with an editor where the row size isn't know before-hand. 

A few things I think mine does differently than yours (though I'm not positive),
-it isn't caching row heights
-it uses a user-supplied estimate of row heights to fake a long-scrollbar
-updates the scroll position after rendering a new row to reconcile the difference between the expected height and the actual. 

I was wondering what you thought about about this approach, and if foresee any issues with it.

Thanks!

**Comment by caseywebdev** [comment]
To be clear, your use case is a list of items where you know the number of total items but you don't know the height of the row for a given item until you've rendered it? You mention using a height estimate, but I'm not sure you can have a smooth user experience if you have to shift the height of the row from the estimated height to the actual height once the user scrolls there. This package avoids that problem by allowing you to provide the exact item size before it's rendered, or in the case that that's not possible, not rendering anything until that row is within the threshold.

**Comment by tnrich** [comment]
"To be clear, your use case is a list of items where you know the number of total items but you don't know the height of the row for a given item until you've rendered it?"
**Yup!**

You mention using a height estimate, but I'm not sure you can have a smooth user experience if you have to shift the height of the row from the estimated height to the actual height once the user scrolls there. This package avoids that problem by allowing you to provide the exact item size before it's rendered, or in the case that that's not possible, not rendering anything until that row is within the threshold.
**I think you're somewhat correct. If you look at the [demo](http://tnrich.github.io/react-variable-height-infinite-scroller/), you'll see that although the side scroller jumps around a bit, but the scrolling itself is smooth because of a call that manually reconciles the scroll height after the new item is rendered. The main issue with this, is that if it takes a long time to render the new item, the scrolling does get choppier. **

**Comment by caseywebdev** [comment]
I think caching the height of previously-rendered rows would be a good idea. You do have to worry about the height of those rows potentially changing if the viewport changes (think text wrapping to a new line, etc), but generally that's not going to happen. If the jumpy scrollbar isn't an issue for you, that approach looks like it'll work well.
