### ISSUE TITLE
How to force a call to itemRenderer?

### ISSUE THREAD

**Issue by Jon4thanGarcia** [orgsync/react-list#36]
I am having some issues where the items in the react-list are not getting re-rendered when the underlying item component's props are updated.

For example, what I am trying to accomplish is that when the user selects an item in the list I want to make an icon visible in my item component. I do this by dynamically setting a flag. I have something like this in my itemRenderer:

```
// There is a hash of the selected item indices in my state
return <MyItem shouldShowIcon={this.shouldShowIconForItemAtIndex(idx) />}
```

On the initial load of the react-list it shows the selected states properly. However, when I select a new item and the state updates in my component the render function gets called, but not the itemRenderer calls. Any ideas on how to notify the react-list to force an update?

**Comment by caseywebdev** [comment]
The most direct thing you can do is call `forceUpdate()` on the list component. Alternatively (and in my opinion, preferably) pass a sort of transitive prop to the list that changes when you want the list to be updated. For example

```js
shouldShowIconForItemAtIndex(i) {
  return i === this.state.theValueThatDeterminesIconness;
},

renderItem(i) {
  return <MyItem shouldShowIcon={::this.shouldShowIconForItemAtIndex(i)} />;
},

render() {
  return <ReactList
     ...
    itemRenderer={::this.renderItem}
    updateWhenThisValueChanges={this.state.theValueThatDeterminesIconness}
  />;
}
```

Here we're passing ReactList a prop (`updateWhenThisValueChanges`, though it could be called anything) so that when it sees that prop change it will rerender each list item.

**Comment by Jon4thanGarcia** [comment]
Thanks. That worked beautifully. Instead I just pass the entire selected indices hash as a prop since there can be many selected components:

```javascript
render() {
  return <ReactList
     ...
    itemRenderer={::this.renderItem}
    updateWhenThisValueChanges={this.state.selectedIndices}
  />;
}
```

Thanks for the help and great job on the library! Closing :+1:

**Comment by caseywebdev** [comment]
No problem, glad it's working for you.

**Comment by dellasys** [comment]
Hi @caseywebdev ,

My ReactList didn't re-render when I changed the state of theValueThatDeterminesIconness that being passed to the ReactList in your example. 

In my scenario, I want to flag the child component with a bookmark icon if user performs "Bookmark" onClick action on each child component. 

I've tried the code above, but still unable to make it re-render.

In fact, what is the method that need to be triggered to re-render the ReactList?

```
constuctor(props){
   super(props);
  this.state = {
     allRequests: props.allReq,     //My entire list of object
  }
}

shouldShowBookmarkForItemAtIndex(i){
      return this.state.allRequests[i].status
  }

renderItem(index) {
    let req = this.state.allRequests[index];   
      return  <myItem
          request={req}
          shouldShowBookmark={this.shouldShowBookmarkForItemAtIndex(index)}/>
  }
render(){

return  <ReactList
               itemRenderer={this.renderItem.bind(this)}
               updateWhenThisValueChanges={this.state.allRequests}
               length={allRequests.length}
               type='simple'
               />
}

```
