### ISSUE TITLE
Please, use translate3d instead of translate

### ISSUE THREAD

**Issue by ezsper** [orgsync/react-list#38]
I'm using this on a mobile app, `translate` is very slow as it don't make use of the GPU, you can just make a 3d option available, I'm not forking it just for this, but I had to replace the whole render function to make use of it. This is a great plugin, it will fit my needs with this option.

**Comment by caseywebdev** [comment]
Sounds good, thanks for the suggestion.

**Comment by caseywebdev** [comment]
Released in `0.6.2`

**Comment by caseywebdev** [comment]
@ezsper after using `translated3d` for a while, I noticed several outstanding graphical issues in Safari regarding `translate3d` but not `translate`. Additionally, IE <= 9 doesn't seem to support 3d transforms. I've decided to take up your original suggestion and make it an opt-in property. `useTransform3d` is now a prop in `0.6.3` and the 2d `translate` is the default.

**Comment by ezsper** [comment]
you may want to use the following instead of transform 3d instead.

    transform: translate(x, y) translateZ(z);

It will force the GPU but it probably wont break in the scenarios you described. I'm using your module together with iScroll, i had to do some adjustments to make it sync with iScroll instead of native scroll, and iScroll use this approach instead of translate3d.

**Comment by caseywebdev** [comment]
Just tested that and I still hit the same Safari bug (https://bugs.webkit.org/show_bug.cgi?id=68196). I'm going to leave it as an opt-in.
