### ISSUE TITLE
Error trying to create a table. 

### ISSUE THREAD

**Issue by sms1983** [orgsync/react-list#39]
I'm trying to create a table using your component, but I could not figure out how. Please, help. 

On almost every attempt I got this error: 

```
Uncaught Error: Invariant Violation: findComponentRoot(..., .0.0.0.0.1.1.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

The generated structure seems to be fine (table>tbody>tr>td). I also passed the ref={ref} to the tbody, but could not avoid that message.

This is what I'm doing...

---
                  <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    
                    <ReactList
                        itemRenderer={this.renderItem}
                        itemsRenderer={this.renderItems}
                        length={listLength}
                        type='variable'
                    />
                </table>
---
```javascript
  renderItems: function(items, ref) {
        if(items.length == 0) {
            return (
                <tbody style={{overflow: 'auto', height: 200}} ref={ref}>
                    <tr>
                        <td> nothing here </td>
                    </tr>
                </tbody>    
            )
        }
        else {
            return(
                <tbody style={{overflow: 'auto', height: 200}} ref={ref}>
                    {items}
                </tbody>
            );
        }
    },
```
---
```javascript
renderItem: function(index, key) {
    	var submission = this.state.submissions[index];
    	if(submission) {
        	return (
                <tr key={key}>
                    <td>
                        {index} - {submission.id} - {submission.title}
                    </td>
                    <td>
                        {index} - {submission.id} - {submission.title}
                    </td>
                </tr>
        	);
        }
        else {
            this.loadMore(index);
            return (
                <tr key={key}>
                    <td>
                        <Spinner/>
                    </td>
                    <td></td>
                </tr>
            );
        }
  	}
```
--

BTW, I don't know if it's important, but the ".0.0.0.0.1.1.0.0" is the data-reactid of the tbody. The data-reactid of the table around it is .0.0.0.0.1.

**Comment by caseywebdev** [comment]
Unless you're using the `simple` type, `ReactList` [uses two wrapper elements](https://github.com/orgsync/react-list/blob/master/react-list.es6#L355) to make the positioning work correctly. Your options are use the `simple` type if that's feasible for your use case, or draw the entire table (including the `<table>` and `<thead>` sections) inside `itemsRenderer`.

**Comment by neverfox** [comment]
I still cannot figure out tables. I changed the example to 'simple' and there's no scrolling. It seems to be only rendering what's on the screen, but the whole page scrolls, not just the table rows with a fixed header as I would expect.

**Comment by caseywebdev** [comment]
I worked up an example for you: https://jsfiddle.net/gzw3jspk/2/

If you want fixed headers like you mentioned, you can't use the traditional `<table>` tags, as you'll notice in my example.

**Comment by neverfox** [comment]
Thanks!

**Comment by neverfox** [comment]
That was very helpful. Playing around with some of the techniques used [here](http://salzerdesign.com/test/fixedTable.html), it does look like you can get it to work with actual table elements, however React will warn about incorrect nesting.

**Comment by Venryx** [comment]
There's a good example of using react-list with actual table/th/tr/td elements here: https://github.com/coderiety/react-list/issues/47#issuecomment-267654182

I use the approach shown there in my project and it works great.
