### ISSUE TITLE
uniform=false does not remove element from the dom

### ISSUE THREAD

**Issue by trungpham** [orgsync/react-list#4]
It seems that I need to set uniform=true in order for the previous elements to be removed from the DOM.

**Comment by caseywebdev** [comment]
This is intentional. We can't ensure the height of elements when uniform is `false`, so we must keep them in the DOM. It isn't sufficient to store the height they were last seen at, because that height could very likely change in the event of a window resize, and then everything is busted.

**Comment by trungpham** [comment]
that makes sense.
