### ISSUE TITLE
Trigger events 

### ISSUE THREAD

**Issue by jtangelder** [orgsync/react-list#41]
It would be nice if the component would accept some callback methods like `onScrollStart`, `onScrollEnd`, `onEndReached`. Since it is an infinite scrolling component, it would be nice to know when to load the next items from a webservice.

**Comment by caseywebdev** [comment]
What use case would those solve that can't be handled already? I don't want to expand the API unless it solves a currently unsolvable problem.

**Comment by jtangelder** [comment]
I guess a `onScroll` handler would be nice if you want to load dynamically new items based on the scroll position (inifinite scrolling!). I don't see any current method which could be used for this. The `itemRenderer` and `itemsRenderer` could be misused for this, but it are render functions.

**Comment by caseywebdev** [comment]
> misused for this

I'm going to have to disagree. `itemRenderer` is passed the `index` that `ReactList` wants to render. This use really all of the information you need. Yes, you need to *return* a renderable item from that function, but it's also a perfect time to bake in your "I know I'm at this point in the list, do I need to fetch anything?" logic before returning. What would happen with an `onScroll` is you'd end up re-doing the math `ReactList` has already done for you (figuring out where in the list you are) and then doing the same thing anyway.

We use this component in production for dynamically loading tables that are thousands of rows and up to hundreds of columns without an issue.

**Comment by CoffeeKitty** [comment]
It is a violation of React API, if `itemRenderer` is used for data fetching. `itemRenderer` is called from `render`, and React requires `render` to be a pure function.

To quote React documentation (http://facebook.github.io/react/docs/component-specs.html):

The render() function should be pure, meaning that it does not modify component state, it returns the same result each time it's invoked, and it does not read from or write to the DOM or otherwise interact with the browser (e.g., by using setTimeout).

**Comment by thornelius** [comment]
> The render() function should be pure, meaning that it does not modify component state

I have to side with @caseywebdev  on this one. Modifying state, DOM read/writes, or browser interaction is not being done at all if you correctly follow the FLUX paradigm.  All you should do is kick off an action to load more data once you are near the end of the list. The loading, success, error states of your request will get propagated down from the action -> store -> view.

**Comment by CoffeeKitty** [comment]
IMHO, FLUX is unrelated here. React API is talking at a lower level, and should be compatible with any paradigm.

You can't really fire a FLUX action with a pure `render` function. To fire a FLUX action in the low level, you'll want to use an AJAX call, kick off a browser timeout, or mutate some variables outside `render`. But these aren't really allowed in a pure function. :( For more information about 'pure function', maybe Wikipedia is a good start: https://en.wikipedia.org/wiki/Pure_function.

If we are careful enough, maybe we *can* use `itemRenderer` to fetch data. But this requires us to be *very careful*, as React expects `render` to be pure; it is possible for React to call `render` multiple times, cache its results, and/or whatever React likes. However, I do not recommend this approach, as this adds complexity and potential pitfalls in the software.

**Comment by caseywebdev** [comment]
You'd have to be just as careful with an `onScroll` event, so I don't really see that as an argument. Something like an `onScrollEnd` event is subjective, and I find that fetching while the user is still scrolling is perfectly desirable as well.

**Comment by CoffeeKitty** [comment]
> You'd have to be just as careful with an onScroll event

Note that if we add an `onScroll` function, it should not be called from `render`. Thus we will have one less thing to worry about, i.e. `itemRenderer` is actually expected to be pure. Calling `onScroll` outside `render` probably add complexity to the library, but it will be fully compatible with React.

Maybe all we need for data fetching is an `onRender(index)` callback triggered outside `render`. I agree that `onScroll*` functions is not necessary for basic use, but it may be beneficial in some cases.

**Comment by caseywebdev** [comment]
`onRender` already exists and it's called `itemRenderer`. If you're doing a synchronous fetch for some reason (ideally you would have already provided that data to ReactList to begin with since it's synchronous), defer your state change with a callback. The much more common use case is signaling some async event to fetch more data in which case there is no synchronous mutation going on, which invalidates your points.

**Comment by CoffeeKitty** [comment]
> The much more common use case is signaling some async event to fetch more data in which case there is no synchronous mutation going on

It seems that *pure function* is misunderstood. You can't really signal any async event in a *pure function*; any async events fired are side-effects of that function, and are not allowed in a *pure function*.

A pure function can never change its 'external environment', so it can never signals for the data fetching.

**Comment by caseywebdev** [comment]
Do you have an actual problem you're trying to solve regarding ReactList usage? I'm not interested in debating semantics.

**Comment by jtangelder** [comment]
Sad to see that this issue is closed. A simple onRender(index) would be a great addition. I agree that discussing about the semantics is a waste of time, but in this case it isn't about semantics, but about correct working of the component! A render should only do a render, and an event should only do the event.

**Comment by caseywebdev** [comment]
> correct working of the component

I can assure you the component works correctly :+1: If you can show me otherwise I'd be happy to fix it.

**Comment by CoffeeKitty** [comment]
No observed problems here. Thanks for this great piece of software. :)

However I am really fearing about potential subtle bugs in the future. I have been following React development, and it seems that they are adding more optimizations, which may rely on the assumptions such like `render` is pure. Currently, `render`, `componentWillReceiveProps` and others are called in a relatively fixed pattern, but this may not be true in the future.

I personally have been following the API very carefully, and would love to point out such subtle issues of ReactList.

**Comment by CoffeeKitty** [comment]
Here is a related issue, please read sebmarkbage's comment:

https://github.com/facebook/react/issues/4067#issuecomment-110792425

**Comment by thornelius** [comment]
I understand your worry about making it a pure and how you want to avoid side effects in itemRenderer. I don't see how this is a react-list issue though. If you are concerned about stuff being pure then react-list is pure in the fact that it does one thing and does it very well, render lists/grids. Anything else should be separated out into its own implementation. So in the use cases mentioned above there would be a separate module for handling different scroll events.

**Comment by CoffeeKitty** [comment]
I agree that ReactList does one thing and does it very well. It is the reason I picked this library out of several similar ones, and am here arguing in the first place.

The problem here is that ReactList does not directly provide much API for notifying list status. Yes, we have `itemRenderer`, but it isn't usable for any side-effects (e.g. dynamic content loading) if we want to follow React API strictly.

**Comment by thornelius** [comment]
>  and am here arguing in the first place.

I wouldn't say arguing... It is more of a discussion.

> The problem here is that ReactList does not directly provide much API for notifying list status.

As I don't think it should. I feel like ```react-list``` should only render lists/grids.  If you are familiar with other platforms that follow this same pattern, of view recycling, they do the same thing. For example, Android's ```ListView``` does not provide a way for notifying list status directly. The same goes for iOS's ```UICollectionView`` and ```UITableView```. If you want to get the list status you have two options in those platforms:

1. Hook into the function to get the view (equivalent to ```itemRenderer```). I think this is the most trivial way of doing it.
2. Hook into the underlying scroll view and handle your scroll events there.

They are proven models and many thousands of apps follow these approaches.

**Comment by CoffeeKitty** [comment]
Well, thanks for the information, as I don't have any experiences with other platforms. Now I understand that ReactList tries to be minimal and follow the common pattern.

Based on these information, I would suggest the following:

We can actually do some tricks to move `renderItem` to be called outside `render`. We can (1) pre-render the items in `componentWillMount`, `componentWillReceiveProps` and whenever ReactList component state is changed; (2) and then cache the results in the component state. If React is used correctly, then we should have all the information as component props and states when pre-rendering. We'll have the same minimal API by then, but `renderItem` can then be safely used for side effects (it can even safely call `setState` of any component, and React can gracefully handle this).

Maybe `renderItem` should be renamed to `getItem` to avoid confusion.

If this suggestion is accepted, maybe we should open a new issue for this.

**Comment by CoffeeKitty** [comment]
After putting more thoughts on this, I found a better way. Actually, we need the list items to be React components. The item component will have access to React's lifecycle methods, and we can do dynamic content loading safely there. Fortunately, this can be done without modification to ReactList.

With ReactList, we should do:
```
class ListItem extends React.Component
    componentWillMount: ->
        maybeLoadContent(@props.index)

    render: ->
        <div> { @props.index } </div>

<ReactList itemRenderer={(i) -> <ListItem index={i}/>}/>
```
instead of:
```
renderItem = (i) ->
    maybeLoadContent(i)
    <div> { @props.index } </div>

<ReactList itemRenderer={(i) -> renderItem(i)}/>
```

I believe this should be mentioned somewhere in the documentation, as this encourages correct usage of React.

**Comment by caseywebdev** [comment]
Feel free to use a separate custom component for each list item. You are quite literally doing the exact same thing as just rendering an HTML component with different semantics. Also, because you're using `componentWillMount` you'll have to give each list item component a unique `key` (like `index`), otherwise  `maybeLoadContent` will only be called with the custom component is first initialized. Be warned that initializing new components that way (with `key={index}`) comes at a cost and the list won't be as performant. I'd definitely not recommend that in the documentation.

**Comment by CoffeeKitty** [comment]
Of course I know the performance cost. We need to instantiate 1 component for each rendered item. With ReactList, this number should be quite small (~30?), at least in the most optimized case. These extra component instances seem perfectly ignorable to me.

I am disappointed in this library's attitude towards correctness/robustness. My other issue regarding robustness (https://github.com/orgsync/react-list/issues/31) was also ignored; a solution would be checking for that in fixed time intervals.

**Comment by caseywebdev** [comment]
I like to make practical, result-driven decisions with this project and so far it's been extremely helpful for our company. Please feel free to fork this project and make any modifications you desire. It is MIT licensed so you can republish it as well.
