### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by oliviertassinari** [orgsync/react-list#42]
I'm rendering 100+ items.
Works fine at the beginning. I'm gonna dig into this issue.
![image](https://cloud.githubusercontent.com/assets/3165635/9589408/0f4aa1a2-5026-11e5-8603-5524a1afe15b.png)

**Comment by caseywebdev** [comment]
This will happen when the item sizes change between renders repeatedly. Can you recreate this in a jsfiddle/codepen?

**Comment by oliviertassinari** [comment]
So, this happen on an Cordova Android Phone.
I have an `Uncaught TypeError: Cannot read property 'children' of null` https://github.com/orgsync/react-list/blob/master/react-list.es6#L141

My component looks like
```js
<ReactList itemRenderer={this.renderItem} length={expenses.size} type="uniform"
   expenses={expenses} // Needed to rerender when expenses are updated
/>
```

Before, using `ReactList`, I was rendering the whole list, it was slow but was working correctly.

**Comment by caseywebdev** [comment]
What version of `React` are you using? And I assume this is on the latest version of `ReactList`?

**Comment by oliviertassinari** [comment]
The last call to `updateUniformFrame` trigger a loop function call inside react 
![image](https://cloud.githubusercontent.com/assets/3165635/9592423/acd32d54-503a-11e5-8fc2-a389ec2539d3.png)
I'm using `react@13.3` and `react-list@0.6.3`. That's really weird

**Comment by oliviertassinari** [comment]
Works fine with the `type="simple"`

**Comment by caseywebdev** [comment]
Looks like the android webview could be rendering the uniform items at different heights. [See this comment](https://github.com/orgsync/react-list/blob/7bd24f5472ffadff53801c402a28c346ab455f80/react-list.es6#L146-L149) on how this is problematic.

**Comment by caseywebdev** [comment]
Could you render some solid block at a fixed height (like `<div style={{height: 100}} />`) instead of whatever you're rendering now and see if it still occurs?

**Comment by oliviertassinari** [comment]
Indeed, the height of my components isn't uniform, let's try

**Comment by caseywebdev** [comment]
No problem! There actually is a line mentioning this

> `uniform` This type is preferred when you can guarantee all of your elements will be the same size.

with an explanation as to why, so I think that's sufficient.

**Comment by oliviertassinari** [comment]
You are right. I did read it. And I though, OK, I think that my items have the same height, If not, I will see a truncated one at the button. I wasn't expecting to freeze the UI.
I see 3 options here for the uniforme type
1. Add a troubleshooting section with this issue
2. Computed the height of the first item and apply it to every other items. In case of.
3. Find where this loop is from and fix it.

**Comment by oliviertassinari** [comment]
Let's pick option 1.
