### ISSUE TITLE
get current scroll position

### ISSUE THREAD

**Issue by hohl** [orgsync/react-list#45]
I really like this React component and already used it for a mostly static list of items. However now I want to use it for displaying chat content which of course dynamically adds content at the bottom from time to time. Whenever that happens *and the users scroll position is already at the bottom* I would like to automatically scroll down. 

I see that there is already a method called `scrollTo` and `scrollAround` which may be helpful for that task. However I still need some way to fetch the current scroll position to check if the user already scrolled to the bottom.

**Comment by CoffeeKitty** [comment]
This should probably be done by another library. See this comment: https://github.com/orgsync/react-list/issues/41#issuecomment-137777547

**Comment by caseywebdev** [comment]
@hohl this component doesn't actually contain the scrollable element, that's up to you. By default, if none of the parent elements of the list have an `overflow: scroll/auto` or `overflow-x/y: scroll/auto`, [it will use the window as a scroll parent](https://github.com/orgsync/react-list/blob/b9df86a81f3097767bce0604335142cd47e77a47/react-list.es6#L91-L99).

Basically what I'm saying is the scroll position is used by ReactList, but it's not responsible for it. You should be able to create a ref for whatever your scrollable element is and do some simple DOM math to figure out if it's at the bottom when a new message comes in, and then `scrollTo`/`scrollAround` (whatever suits you best).

**Comment by emilv** [comment]
Check out c36fa0b07d1aa6de109133690b28e15be6d62fdc!
