### ISSUE TITLE
react-list.js:175 Uncaught TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by hohl** [orgsync/react-list#46]
I just updated to the most recent version of `react-list` and scrolling started seem to cause freezes then I looked into the console and found this:

```
Uncaught RangeError: Maximum call stack size exceeded -- react.min.js:13
Uncaught TypeError: Cannot read property 'children' of null -- react-list.js:175
```

Did I missed something? My app worked fine before updating this library.

**Comment by hohl** [comment]
sorry, invalid bug report

**Comment by Secretmapper** [comment]
@hohl Just encountered this. What was the problem?

**Comment by hohl** [comment]
I'm sorry. I encountered some issue in my data source, but already forgot what the exact issue was.
