### ISSUE TITLE
How to use in table rendering

### ISSUE THREAD

**Issue by box-turtle** [orgsync/react-list#47]
Is there a sample of using this for rendering a table? I'm having trouble constructing the itemsRenderer so that the scrolling works correctly. 

Hoping to use this as the basis for a high-performance grid component with fixed/frozen columns.

**Comment by box-turtle** [comment]
Sorry for the quick raising of the issue - found out I needed to put the ref on the tbody element and now things are working fine.

**Comment by caseywebdev** [comment]
Glad it's working out for you.

**Comment by neverfox** [comment]
@box-turtle Do you have a working gist of that?

**Comment by codemonkeynorth** [comment]
leaving this here for anyone who gets stuck...

```javascript
// our outer table, to pass to itemsRenderer
renderTable (items, ref) {
  return (
    <table className="myTable">
      <thead>
        <tr> 
          <th>name</th>
          <th>score</th>
        </tr>
      </thead>
      <tbody ref={ref}>
      {items} // this is where our ReactList items render
      </tbody>
    </table>

// our main list render function
renderScoresTable() {
  <ReactList
    itemsRenderer={(items, ref) => this.renderTable(items, ref)}
    itemRenderer={this.renderRow}
    length={this.state.scores.length}
    type="uniform"
  />      
}

// individual row render
renderRow(index, key) {
  let entry = this.state.scores[index]
  let userName = entry.userName;
  let score = entry.score;
  return (
    <tr key={key}>
      <td className="name">{userName}</td>
      <td className="score">{score}</td>
   </tr>
  );
}
```

**Comment by STRML** [comment]
Thanks @codemonkeynorth, it wasn't obvious that the ref needed to be on the `<tbody>` and not the `<table>`, saved me a bit of headache with a scroll issue.
