### ISSUE TITLE
Support of React v0.14

### ISSUE THREAD

**Issue by oliviertassinari** [orgsync/react-list#48]
Facebook has released a candidate for [v0.14](http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html), but we can't use it with `react-list` (needs react@0.13.x).

**Comment by caseywebdev** [comment]
`react@0.13.x` and `react@0.14.x` are both now supported in `react-list@0.6.4`

**Comment by oliviertassinari** [comment]
@caseywebdev Thanks!
