### ISSUE TITLE
does not render in nodejs

### ISSUE THREAD

**Issue by trungpham** [orgsync/react-list#5]
when using uniform=false

**Comment by caseywebdev** [comment]
Can you elaborate? I believe the only place a DOM is assumed is in `update`, which shouldn't be called in Node as it's kicked off in `componentDidMount`, which shouldn't be called if you're using `React.renderToString`.

**Comment by trungpham** [comment]
I believe this has to do with me using the state as the data source. And setState does not synchronously trigger the render function.

**Comment by trungpham** [comment]
I think the problem with is with this line.

https://github.com/orgsync/react-list/blob/master/react-list.js#L63

the initial length is 0. so the initial renderItems never took place.

length should be props.items.length instead of zero.

**Comment by caseywebdev** [comment]
Fixed and released in `0.2.9`, thanks for reporting!

**Comment by trungpham** [comment]
thank you. it's working great now.
