### ISSUE TITLE
Getting an infinite 're-rendering' loop in variable mode

### ISSUE THREAD

**Issue by dozoisch** [orgsync/react-list#56]
Hi,

I have a list of items that are of different sizes, ranging from 40px to 75px. In "simple" mode it renders just fine. It happens on both chrome in mobile emulation mode and Simulator Safari (I have -webkit-overflow touch in safari)

```jsx
<ReactList
  useTranslate3d
  initialIndex={this.state.preloadRowStart}
  itemRenderer={this.renderRow}
  length={this.state.rows.length}
  type="variable"
/>
```
These are the parameters I'm using. I'm don't have an `itemSizeGetter`

In variable mode it sometimes get in a render loop. I've put a few `console.log`. 

In updateVariableFrame: `console.log(from, size);`
In render: `console.log('render');``
In componentDidUpdate: `console.log('update');`

![image](https://cloud.githubusercontent.com/assets/4422516/10238245/1a91f236-688b-11e5-89bb-0d726c8b6852.png)

As you can see, it keeps running updateFrame and get a 1 off result every time, so it triggers a rerender which triggers an componentDidUpdate, which triggers updateFrame, etc. The loop causes  the browser thread to freeze until maximum call stack size occurs.

I'm still investigating it to see why it's happening. I'll give you more details as I have more, but just wanted to let you know.

The length is of about 30 elements right now.

More info coming soon.

**Comment by dozoisch** [comment]
More data
with `console.log(from, size, space, start, end);` in updateVariableFrame

So as from and size, start and end keeps switching.

![image](https://cloud.githubusercontent.com/assets/4422516/10238486/6f76e984-688e-11e5-9837-202554cdd4b2.png)

**Comment by dozoisch** [comment]
Odd enough is seems to be caused by margin/padding

```
.header {
  margin-top: 2em;
}

.round {
   padding: 0.4em 0;

   & + .firstRound {
     margin-top: 1.2em;
   }
```

This is the css im using, where my list looks a bit like

```
header
.round.firstRound
.round
.round
.round.firstRound
.header
.round.firstRound
.round.firstRound
.round
.round
```

When I remove all margin padding, the issue vanishes.

**Comment by caseywebdev** [comment]
Yup, the overlapping nature of margins makes them not reliable for determining element size, so it's always better to space with padding. I'm hesitant to add notes to the documentation for every issue that pops up, especially since Google is pretty good at directing people to relevant GitHub issues.
