### ISSUE TITLE
Finding out the index of the current first item

### ISSUE THREAD

**Issue by Secretmapper** [orgsync/react-list#57]
In my current use case, I'm creating two scrollable lists which are 'synced' with each other.

I thought of using `scrollTo` to scroll to the current first item of either one of them. However I have not found any part of the docs to address getting the current index of the first visible item in a react-list.

**Comment by emilv** [comment]
This would also help us to implement things such as scrollspy.

**Comment by caseywebdev** [comment]
I'm thinking adding a method like `getVisibleRange` that returns `[i, j]` where `i` is the first visible element and `j` is the last would be the most flexible way to handle this.
