### ISSUE TITLE
Rendering problems when scrolling fast

### ISSUE THREAD

**Issue by evgenyzinoviev** [orgsync/react-list#58]
I have a bug that can be best described by the video: https://youtu.be/tRR0EIifrX4
It happens in Chrome, Mac OS.  When a cursor is over a scrollbar (or when I scroll by dragging a slider instead of using trackpad or mouse), there is no problem. But if it somewhere over a list, strange things happening.

ReactList is created like this:
```
<ReactList itemRenderer={this.renderItem} length={this.state.friends.length} type="uniform" />;
```
It happens with `type="variable"` as well.

Any hint of how to fix it is highly appreciated.

**Comment by caseywebdev** [comment]
That's definitely strange. You might try the prop `useTraslate3d={true}` and see if that helps. Fortunately, scrolling up and down rapidly is not a real use case, so this shouldn't hurt usability.

**Comment by evgenyzinoviev** [comment]
Already tried useTranslate3d, no effect.

**Comment by caseywebdev** [comment]
As a test, you could try adding `style={{pointer-events: 'none'}}` to those list items and see what happens. I'd imagine the browser has to do more work when you're hovering over *clickable* elements vs elements that are complete static.

**Comment by evgenyzinoviev** [comment]
No, still the same.
Probably in this video the effect can be seen better: https://youtu.be/47U5rKdlbLU

When I scroll heavily, an empty space between the edge of the screen and the list is quite large, but it decreases and disappears as scrolling slows down (the OS X inertial scrolling effect). Maybe it has something to do with this inertial scrolling.. just a theory.

**Comment by caseywebdev** [comment]
Have you tried increasing the `threshold` to something higher than the default? This will render more elements above and below the visible area, which might help your case. If that doesn't do it, I'm not sure what else we can do. Seems like it might just be the side effect of a Chrome rendering optimization.

**Comment by evgenyzinoviev** [comment]
Just tried, not really helpful - it works a little bit better on slow speeds, but still blinks (even worse) on high speeds.

Sad to hear that, maybe someone else have faced this problem and will share a solution or a workaround.

**Comment by caseywebdev** [comment]
Seeing as this isn't really a usability problem and there's no known way to address this, I'm going to close this issue. Feel free to comment further if you find a helpful solution.

**Comment by evgenyzinoviev** [comment]
I just accidentally found a solution! You have to attach `mousewheel` listener to the scrollable element. Just an empty listener. After that `onscroll` events will be fired synchronously. 

Chrome, you are crazy.

**Comment by gch1p** [comment]
Suggested fix is not working for me in recent versions of chrome. So I invented a new one. The idea is that you attach `wheel` listener that cancels the event and updates `scrollLeft` and `scrollTop` properties of scrollable div. Example:
```
  onWheel = (e) => {
    e.preventDefault();
    this.scrollParent.scrollLeft += e.deltaX;
    this.scrollParent.scrollTop += e.deltaY;
    return false;
  }
```
