### ISSUE TITLE
Does not work in Firefox since 0.7.1

### ISSUE THREAD

**Issue by emilv** [orgsync/react-list#59]
react-list scrolling stopped working in Firefox in version 0.7.1. I have tried 0.7.0 (works), 0.7.1 (does not work) and 0.7.2 (does not work). We have React 0.14.0 in all cases.

I do not get any error message in the web browser console. I do get the first "page" of rendered items, and the container div is created with the right height. It is just that when I scroll no new items are rendered.

I cannot reproduce the bug in webkit-based browsers.

**Comment by caseywebdev** [comment]
Hmm it does look like something weird is going on.

**Comment by caseywebdev** [comment]
From what I can see this is only affecting lists where the scrollParent is `window`. Is that your case?

**Comment by caseywebdev** [comment]
Should be fixed in `0.7.3`

**Comment by emilv** [comment]
Awesome! I did indeed have window as scrollparent and this resolved the bug. Great work!
