### ISSUE TITLE
IE9 support?

### ISSUE THREAD

**Issue by box-turtle** [orgsync/react-list#62]
Has anyone verified whether this works on IE9? I don't get any errors, but after I scroll past the initial rows the scrolling area is blank. If I scroll back up the initial rows are there. 

I made sure I am using translate rather than translate3d.

To be clear - not asking for any enhancement here, just trying to confirm behavior. Really enjoying using this lib.

**Comment by caseywebdev** [comment]
Our product officially supports IE >= 10, so IE9 falls out of our target browser range. If you want to hunt down the problem/solution for IE9 we can merge that in.
