### ISSUE TITLE
Scroll event handler?

### ISSUE THREAD

**Issue by mauricesvay** [orgsync/react-list#63]
Having a scroll event handler could be useful for loading more items when reaching the bottom of the list.

**Comment by caseywebdev** [comment]
Simply use `onScroll` on whatever element contains your list.

```js
<div style={{height: 300, overflow: 'auto'}} onScroll={this.handleScroll}>
  <ReactList ... />
</div>
```

ReactList does not own the scrollable element.

**Comment by caseywebdev** [comment]
You may also be interested in the `getVisibleRange()` function. For example...

```js
handleScroll() {
  const [firstVisibleIndex, lastVisibleIndex = this.list.getVisibleRange();
  if (lastVisibleIndex >= theIndexIWantToLoadMoreAt) loadMore();
}

render() {
  return (
    <div style={{height: 300, overflow: 'auto'}} onScroll={this.handleScroll}>
      <ReactList ref={c => this.list = c} ... />
    </div>
  );
}
```

**Comment by mauricesvay** [comment]
Thanks! I didn't realize that the scroll was on the parent and that I could listen to this event.

Thanks for your help!

**Comment by caseywebdev** [comment]
No problem

**Comment by tnrich** [comment]
Any chance this info could go into the docs? It took me awhile to find it here in the issues. 

Thanks!

**Comment by caseywebdev** [comment]
If you'd like to add it to the FAQ section feel free to open a PR.

**Comment by tnrich** [comment]
I PR'd it: #150

**Comment by SoloJiang** [comment]
Cool!

**Comment by BeckhamVinoth** [comment]
@all ,   Am using this.list.getVisibleRange() .. this is returning me undefined . ..any idea on this ?

**Comment by BeckhamVinoth** [comment]
const [firstVisibleIndex, lastVisibleIndex] = this.list.getVisibleRange(); 
 // in console ---->    [undefined, undefined]

**Comment by funk101** [comment]
is it possible to access getVisibleRange() within an es6 functional component? All the examples show it available using the "this" keyword -> this.getVisibleRange(). How can I implement this method without defining in a class?
