### ISSUE TITLE
Unload pages 

### ISSUE THREAD

**Issue by Antho2407** [orgsync/react-list#65]
Hi, I am currently using your component and it's working well, but I was wondering if it was possible to unload previous pages (and having the same behaviour when the user wants to get back to the top)

Anyway thanks for the component, it's great !

**Comment by caseywebdev** [comment]
Please [check out the `type` prop](https://github.com/orgsync/react-list#type-one-of-simple-variable-or-uniform-defaults-to-simple). DOM elements above the viewport will be removed if you use the `variable` or `uniform` type. The type you choose depends heavily on your use case.
