### ISSUE TITLE
Infinite rerender in admittedly niche use case

### ISSUE THREAD

**Issue by tquetano-r7** [orgsync/react-list#66]
So I am building a table right now, and within this table there can be nested items ... this is being accomplished by adding a row to the data set that has a single td with colSpan=number of columns. Pretty common hack.

Anyways, I naturally created a component that would nest inside of this full-width td, and when I add it in the component infinitely rerenders. A stripped-down version of what I mean:

```
renderItem(i, key) {
...
    if (isExpandedRow) {
        return <tr>
            <td
                colSpan={this.state.columns.size}>
                    Test
            </td>
        </tr>;
    } else {
        // build rows
        return <tr>
            {rows}
        </tr>;
    }
}
```

Obviously this lacks the keys and all that jazz, but you get the idea. Now, this setup works just fine, however when I switch out "Test" for my component ... boom.

```
renderItem(i, key) {
...
    if (isExpandedRow) {
        return <tr>
            <td
                colSpan={this.state.columns.size}>
                    <MyComponentThatWorksJustFine />
            </td>
        </tr>;
    } else {
        // build rows
        return <tr>
            {rows}
        </tr>;
    }
}
```

Now, when I say boom, its not automatic. Only when I scroll down and updateFrame is triggered does the infinite re-render begin. My hunch is that its due to the fact that the itemsPerRow differs each time, and you appear to be calling eventually calling setState on componentDidUpdate ... so it updates ad-infinitum.

 Any ideas?

**Comment by caseywebdev** [comment]
Sounds like you're using the `uniform` type? If so, are all of your items always an identical size? That is a prerequisite for using the `uniform` type, and this situation can arise when it's not met.

**Comment by tquetano-r7** [comment]
Ah bugger ... you're right, I'm using uniform. I guess I'm learning how to use the itemSizeGetter so that I can ensure the scrollbar doesn't "magically grow".

Thanks man, appreciate the help.
