### ISSUE TITLE
rendering varying amount of horizontal elements

### ISSUE THREAD

**Issue by piranha** [orgsync/react-list#67]
Hi! For start, I should say I'm really happy with this component, it's been a savior for me. :)

There is one thing I would like to ask though. We're rendering list of products alongside with sidebar (for filtering those products). So we have 3 products in a row, and when sidebar ends, we render 4 products in a row. Flowing around sidebar, as you can imagine.

In those conditions react-list starts reflowing my products in a weird way, having 3 products in a first line, and then lines with 4 of them. I recorded [a video of that effect](https://monosnap.com/file/tr39ullPR02CiwzYvpEm4fmt0ECCpH). 

I wonder if it's possible to make it work properly or we should rethink our interface?

**Comment by caseywebdev** [comment]
Your best bet would be to render some "invisible" items for indices 0, 4, and 8 that take up the same amount of space as actual items and this would allow you to keep a consistent 4xN grid. Alternatively, render two lists on top of each other with the first one limited to those first 9 products (3x3) and the second with the rest (4xN).

**Comment by piranha** [comment]
Hm, that makes sense, I'll try both approaches, I guess, thanks.
