### ISSUE TITLE
Pass explicit scrollParent as props

### ISSUE THREAD

**Issue by jquense** [orgsync/react-list#68]
Hi there, thanks for the excellent component, it has been a pleasure to not have to write another virtual list implementation in react, since your is top notch.

Question: I have a situation where the eventual scroll parent of my list doesn't actually have an overflow when the component mounts defeating: https://github.com/orgsync/react-list/blob/master/react-list.es6#L106

Would you be open to a PR allowing the scroll parent to be specified via props for cases like this?

**Comment by caseywebdev** [comment]
That seems reasonable, but maybe we can resolve this without expanding the API. Can you explain your use case a bit?

**Comment by jquense** [comment]
Sure.  it's honestly a bit tough to explain but I'll try.  essentially it's an affixed (position: sticky) side panel. At the top of the viewport the side panel is  inline and the scroll bar is hidden. it's only as you scroll down and the side panel switches to position: fixed,  that the scroll parent gets its scroll bar. it is more of a UX thing than anything else but it essentially requires the user to scroll the window down so the side panel takes up the whole viewport before they can scroll that.  this keeps them from the awkward two scrollbars on the page and scrolling something that is also partly hidden by the viewport. 

which is a lot to say that we explicitly set overflow of the side panel to hidden  at window scrollTop 0, and then turn it to 'auto' later. needless to say react-list thinks the scrollParent is the window when it ultimately isn't. I might be able to do some div nesting  and height setting to keep the 'auto' always on in the right place, but initial attempts have resulted in a bunch of extra markup we'd like to avoid. 

if it's helpful I can try and provide some code a bit later (on my phone now)

**Comment by caseywebdev** [comment]
Could you please try the build from my `update-scroll-parent` branch? https://raw.githubusercontent.com/orgsync/react-list/update-scroll-parent/react-list.js

Some perf testing showed that updating the scroll parent on frame updates has a negligible cost.

**Comment by jquense** [comment]
Thanks for the quick attempt, very appreciated. I gave it a whirl, it doesn't quite help our use case unfortunately, the problem is that when the scrollParent shifts, react-list doesn't actually fire an update at that point.

What happens is that the initial SP (the window) gets scrolled to the bottom, at which point the inner div gets `overflow: auto`, since react-list is running update frame onScroll, it missing the switch (I assume because the scrolling is done when the switch happens). That leaves you scrolling the inner DIV but the list isn't watching its onScroll so it just gets to the end of the current rendered frame and stops.

I think this is probably indicative of the sort of problem trying to auto adjust presents. I definitely understand not wanting to increase API surface area though.

**Comment by caseywebdev** [comment]
I'm trying to decide between two options here. Either expose the `updateScrollParent` method so that it can manually be updated when you need it to, or as you suggested, add a `scrollParent` prop and check for it in `componentWillReceiveProps`, and update accordingly. I'm a little hesitant to use the latter as it would allow the user to potentially get in a weird state where their scrollParent might be incorrect or not in the DOM, whereas with exposing the method they'll always have the closest scrollable parent.

Could you try creating a ref to the list and calling `list.updateScrollParent()` when it's appropriate in your case?

**Comment by jquense** [comment]
some form of that would work but it's a bit ugly, since now I have wrap all that up in a bunch of `componentDidUpdate()` calls which will trigger more renders, and extra updates, whereas an advantage to doing the check (did the scrollParent update) in componentWillReceiveProps is that you don't get any extra render calls.

A bit more to the point tho I think you'd need to call `updateFrame` instead of `updateScrollParent` since switching the scroll parent is going to almost certainly need you to re calculate whats on the screen.

While I am thinking about it tho, the other advantage to providing a prop in this case, is that you avoid a whole bunch of unnecessary work in some cases (as in ours). when sniffing the SP the window will get a scroll listener on mount even tho I _know_ that the list should not be listening to the window or doing any calculations at this point. By telling it that my div is the SP no updates will run when scrolling the window.

I definitely agree though that such an option opens the door for folks to do something silly by accident, but perhaps a stern warning in the docs might be enough to help that concern?

**Comment by caseywebdev** [comment]
Let's assume it's a prop, how will the list know to update when you change the style on that containing element?

**Comment by jquense** [comment]
It doesn't need to right? its already rendered the first set of list items calculated from that SP, so its just waiting until you actually scroll on it in which case it will pick up right there. The other case is that you need do need to update the list when the SP changes, but that's easy enough. That all seems to be borne out in our testing as well.  https://github.com/jquense/react-list.

**Comment by caseywebdev** [comment]
I've updated that same `update-scroll-parent` branch to accept a `scrollParentGetter` prop. Try that out when you get a chance.

**Comment by RamIdeas** [comment]
This branch is exactly what I'm looking for!

To avoid scrolling elements within other scrolling elements, I'm setting the inner elements' `overflow` to `hidden` and setting their `scrollTop` manually based on the outer scroller's `scrollTop`. `scroll` events still fire when I do this, but since the elements have `overflow: hidden` in their computed style you ignore them and continue walk up the DOM tree.

Since this branch is now 7 commits behind, any chance you'd consider either updating the branch or just merging it into master?

...Side note:

Another beneficial approach, since I'm already catching `scroll` events, would be to pass `scrollTop` into you as a prop. Perhaps you could have a `ReactListInner` component which `ReactList` was just a wrapper for. It would seperate the concerns of getting data (either from the DOM or from `props`) and using that data (to decide what to render and when). Then, perhaps, I'd be able to use `ReactListInner` directly.

**Comment by caseywebdev** [comment]
I've updated the branch. Could you provide a small working example of what you described? I generally like to see a solid use case for expanding the API.

Regarding a `ReactListInner`, I believe that would put too much burden on the consumer to even be useful.

**Comment by jquense** [comment]
I'd also like to chime back in. Sorry for the delay, life gets busy! the branch is working great for us as well, definitely solves my use case, thanks a ton.

**Comment by RamIdeas** [comment]
Cheers for updating the branch, @caseywebdev! I'm quite busy trying to ship this right now, but I'd happily put something up in a few weeks time.

RE `ReactListInner`: it would only serve those who need it, the `ReactList` component would not change from an API perspective.

...One point on this current branch though:

Don't these 2 lines need to be switched? https://github.com/orgsync/react-list/blob/update-scroll-parent/react-list.es6#L76-L77. I keep getting `TypeError: Cannot read property 'addEventListener' of undefined`. My `scrollParentGetter` hasn't been called yet. `updateFrame` is what calls `updateScrollParent` so you can't use `this.scrollParent` beforehand.

**Comment by caseywebdev** [comment]
Oh that first line should be deleted. I messed that up when I merged master in, good eye.

I'll merge this is and cut a new version.
