### ISSUE TITLE
initialIndex doesn't work on consequtive re-render

### ISSUE THREAD

**Issue by Akudrevatykh** [orgsync/react-list#71]
I've noticed that initialIndex doesn't work well when state of an owner component changes frequently. 

Here is a sample to reproduce the problem. 
Expected: focus scroll on the last(10th) element.
Observed: focus on the first element.

```
import React from 'react';
import ReactList from 'react-list';


const getHeight = index => 30 + (10 * (index % 10));
getHeight.toJSON = () => getHeight.toString();

const renderVariableHeightItem = (index, key) =>
  <div
    key={key}
    className={'item' + (index % 2 ? '' : ' even')}
    style={{lineHeight: `${getHeight(index)}px`}}
  >
    {index}
  </div>;
renderVariableHeightItem.toJSON = () => renderVariableHeightItem.toString();

export default class TestList extends React.Component {
  constructor() {
    super();
    this.state = {numItems: 1};
  }

  componentDidUpdate() {
    if (this.state.numItems < 10) {
      const numItems = this.state.numItems + 1;
      setTimeout(this.setState({numItems}), 1000);
    }
  }

  componentDidMount() {
    if (this.state.numItems < 10) {
      this.setState({numItems: this.state.numItems++});
    }
  }

  render() {
    const props = {
      length: this.state.numItems,
      pageSize: this.state.numItems,
      initialIndex: this.state.numItems,
      itemRenderer: renderVariableHeightItem,
      type: 'variable'
    };

    return (
      <div key={1} className={`example axis-${props.axis}`}>
        <strong>Props</strong>
        <pre className='props'>{JSON.stringify(props, null, 2)}</pre>
        <strong>Component</strong>
        <div className='component'><ReactList ref={c => this.test = c} {...props} /></div>
      </div>
      );
  }
}
```

**Comment by caseywebdev** [comment]
`initialIndex` will only attempt set the scroll position when the component first loads. If you want to scroll the list to a specific index at an arbitrary point, use `scrollTo` or `scrollAround`.

**Comment by Akudrevatykh** [comment]
@caseywebdev Thanks for your answer. 

That effectively means that `ReactList` is not a "pure" component. In other words it doesn't output the exact same markup given the exact same props and state. 

While I understand my sample is not exactly the use case that was intended for `ReactList`... is there any benefit in this design? I think if an owner component didn't have to deal with internal state of `ReactList` it would make it easier to use :)

**Comment by caseywebdev** [comment]
> That effectively means that ReactList is not a "pure" component? In other words it doesn't output the exact same markup given the exact same props and state.

The markup is identical. Scroll position is state outside of markup (and outside of React, for that matter). `initialIndex` is a convenience prop for landing the list at a specific index for the initial render only.

> didn't have to deal with internal state of ReactList

You don't have to know anything about the internal state of ReactList. In fact, scroll position isn't state that ReactList owns, it's stored in the DOM. `scrollTo`/`scrollAround` are public, documented and encouraged. If you'd like to snap the list to the bottom whenever you add an item, use `scrollTo(length - 1)` in your `componentDidUpdate` after that item is added. Alternatively you can just target the scrollable element yourself (ReactList doens't own this element) and set the scrollTop to whatever you'd like.

If you really want to use the `initialIndex` prop, you can probably get it working how you're expecting by providing a unique `key` on every render, therefore creating a new instance of the component every time, but I don't recommend that.
