### ISSUE TITLE
loading more elements

### ISSUE THREAD

**Issue by grisha78** [orgsync/react-list#72]
Hello,
My app cant load all elements in the state, Is there a way to know when the list has reached the end, to load more elements?
I tried to check index in itemRenderer and load more items there, but the state cant be modified in a render phase.

Regards

**Comment by grisha78** [comment]
ok i 've finally got round the problem by modifying the componentDidUpdate method.
I add a call to a property function "onBottom" when from+size>=length-1
onBottom is implemented in the parent by calling an underlying REST service and updating the state, this re-render the list and all is working fine.

By the way do you think such feature could be added in a future version ?

**Comment by caseywebdev** [comment]
Please see previous issues about this. `ReactList` is intended to be a lower-level component that you should build on with whatever makes sense for your data.
