### ISSUE TITLE
Don't set style height when it is unknown

### ISSUE THREAD

**Issue by Akudrevatykh** [orgsync/react-list#74]
Hey, it's me again :) 

I was wondering if on initial render with type `variable` (when size of list items is unknown) `react-list` could skip setting the div's style to 0. Basically something like this in the render function:
```
const size = this.getSpaceBefore(length, cache);
    if (size) {
      style[SIZE_KEYS[axis]] = size;
    }
```

Currently if I want to position my elements at the bottom of the container they get pushed below it's bottom border due to `height:0`. Here is a sample to illustrate the issue:
```
import React from 'react';
import ReactList from 'react-list';


const getHeight = index => 30 + (10 * (index % 10));
getHeight.toJSON = () => getHeight.toString();

const renderVariableHeightItem = (index, key) =>
  <div
    key={key}
    className={'item' + (index % 2 ? '' : ' even')}
  >
    {index}
  </div>;
renderVariableHeightItem.toJSON = () => renderVariableHeightItem.toString();

export default class TestList extends React.Component {
  render() {
    const props = {
      length: 2,
      itemRenderer: renderVariableHeightItem,
      type: 'variable'
    };

    return (
      <div key={1} className={`example axis-${props.axis}`}>
        <strong>Props</strong>
        <pre className='props'>{JSON.stringify(props, null, 2)}</pre>
        <strong>Component</strong>
        <div style={{position: 'relative'}} className='component'>
          <div style={{position: 'absolute', bottom: '0px'}}>
            <ReactList ref={c => this.test = c} {...props} />
          </div>
        </div>
      </div>
      );
  }
}
```

**Comment by caseywebdev** [comment]
I don't think I understand what you're trying to do. Could you put your example in a jsfiddle or codepen to help illustrate?

**Comment by Akudrevatykh** [comment]
@caseywebdev https://jsfiddle.net/qsv7ct58/

As you can see list items [1,2] are positioned outside of the container div and a scroll bar is added. I've noticed that in the render function of react-list the outer most div's style is set to "position:relative;**height:0**;" since on the initial render height of all items is unknown.

I was wondering if this can be avoided by ignoring the incorrect height in the render function:
```
const size = this.getSpaceBefore(length, cache);
    if (size) {
      style[SIZE_KEYS[axis]] = size;
    }
```

Thanks for you time.

**Comment by caseywebdev** [comment]
Could you explain what you're trying to accomplish? I removed `type="variable"`, defaulting to the `"simple"` type, and your 2 list items were displayed at the bottom of the screen.

**Comment by Akudrevatykh** [comment]
You are right in this case it's easier to use simple.
