### ISSUE TITLE
`cancelAnimationFrame` is not undefined

### ISSUE THREAD

**Issue by STRML** [orgsync/react-list#78]
This error fires on unmount on browsers not supporting rAF. The issue is this line:

https://github.com/orgsync/react-list/blob/master/react-list.es6#L90

It appears to have been introduced accidentally as RAF was removed but this line was not.

**Comment by caseywebdev** [comment]
Er yea this was definitely overlooked in a merge, I'll remove it.

**Comment by caseywebdev** [comment]
Fixed in `0.7.10`
