### ISSUE TITLE
How to animate `scrollTo`

### ISSUE THREAD

**Issue by jgibbons** [orgsync/react-list#79]
I was wondering what would be the best practice for animating the scrollTo function? Thanks for this great library!

**Comment by caseywebdev** [comment]
Check the source and you'll notice the `top` position of an index is calculated by `getSpaceBefore(index)`, so you can use that to get the raw target `scrollTop` (though it's not documented). Once you have that just use your favorite animation library to set whatever your scrollable element is to animate toward that `scrollTop`.

**Comment by amowu** [comment]
My solution for [react-scroll](https://github.com/fisshy/react-scroll):

```js
import { animateScroll as scroll } from 'react-scroll';

const y = reactListRef.current.getSpaceBefore(target);

scroll.scrollTo(y, {
  container: reactListRef.current.scrollParent,
  isDynmic: true,
  duration: 400,
  smooth: 'easeInOutQuad',
});
```
