### ISSUE TITLE
Update for React 0.13

### ISSUE THREAD

**Issue by blakeembrey** [orgsync/react-list#8]
I tried using the component with React 0.13, but I found that I run into an infinite(ish) rendering loop. I'll continue scrolling down but it'll be rendering the old elements above the fold.

**Comment by caseywebdev** [comment]
I'm not seeing this behavior in the test file with React 0.13.1. Could you provide a jsfiddle/codepen example? Also what browser are you seeing this in?

**Comment by blakeembrey** [comment]
You're right! Sorry, I broke something in my app that causes this to happen.

**Comment by caseywebdev** [comment]
:+1:

**Comment by jordansexton** [comment]
@blakeembrey I'm actually running into this as well. Do you recall what the issue in your app was?

**Comment by caseywebdev** [comment]
I'm not sure if this was @blakeembrey's issue or not, but if you're using the `UniformList` you'll want to make sure your elements are all exactly the same height. Even a one pixel difference is problematic when you're trying to space out thousands of elements. The standard `List` component should be used when height cannot be guaranteed.

**Comment by blakeembrey** [comment]
@jordansexton I can't recall exactly, but it had something to do with the way my styles were being applied. It was weird, so I moved to inline styles and it didn't happen again. Could have been because I was testing some new things with my React style library and forgot it was linked.

**Comment by caseywebdev** [comment]
I wonder if it's worth supporting opt-in `height` and `column` properties that can be used in lieu of automatically calculating those values. Would save some CPU...

**Comment by blakeembrey** [comment]
How much calculations are we talking though? In my project I do know the height and can probably calculate the number of columns in advance. This is probably a topic for another issue too, but I couldn't actually use `UniformList` in my application. I'm using flexbox and since the containing divs didn't set `flex: 1` they don't expand to the full size. Is that something you're willing to fix?

**Comment by caseywebdev** [comment]
> How much calculations are we talking though?

Not much, but providing that information ahead of time might have a significant effect when scrolling quickly.

> Is that something you're willing to fix?

Can you elaborate on the problem you're having? Is a jsfiddle/codepen feasible? Maybe in a new issue.

I'm going to create an issue for the new props.

**Comment by cmwelsh** [comment]
The automatic layout was one of the most pleasant things about using `react-list`. Perhaps it would make sense to add an addition to the README that the first element in the list will be used for calculating layout in a UniformList (i.e. people who care about performance). Developers should be aware to adjust their application code to always return the correct dimensions for each element.

**Comment by caseywebdev** [comment]
[It's there](https://github.com/orgsync/react-list#itemheight-defaults-to-automatic-calculation) :wink: 

I definitely love that feature, but since it's basically free to allow people to explicitly set their height/columns I don't see the harm in making it available.
