### ISSUE TITLE
Component doesn't define main assets in bower.json

### ISSUE THREAD

**Issue by jkbennington** [orgsync/react-list#80]
Hi, I use https://rails-assets.org/ to import react-components into rails. Saw this line:
```
Post-install message from rails-assets-react-list:
This component doesn't define main assets in bower.json.
```
I've seen others have this issue https://github.com/winmarkltd/BootstrapFormHelpers/issues/218. I'll look into this more but if you have a quick-fix that would be much appreciated. 

Best,

**Comment by caseywebdev** [comment]
Well there is a `main` property in `package.json` that points to the correct file. It seems like they should be able to derive that information from there right?

**Comment by jkbennington** [comment]
Unfortunately they only pull from the bower.json file, serving as a proxy between bundler and bower.

**Comment by tfausak** [comment]
This project doesn't have a `bower.json`.

**Comment by jkbennington** [comment]
Apologies, it was listed on rails-assets(which uses bower) for some reason which in turn gave me that error. I've since just loaded it in using browserify as an npm package. Thanks.
