### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by harrybabu** [orgsync/react-list#84]
I am getting this error

Uncaught TypeError: Cannot read property 'children' of null

updateSimpleFrame @ react-list.js:287
updateFrame @ react-list.js:264

What could be the root cause for this issue.

**Comment by harrybabu** [comment]
<ReactList
            itemRenderer={::this.renderItem}
            length={items.length}
            type={'simple'}
          />'

This my configuration...

**Comment by caseywebdev** [comment]
Please reproduce the issue in a jsfiddle/codepen/jsbin/takeyourpick.
