### ISSUE TITLE
Compatibility with CSSTransitionGroups?

### ISSUE THREAD

**Issue by bluejamesbond** [orgsync/react-list#87]
Animate appear, exit, leave animations on items in the list. Since the render strategy of react-list is unconventional (in a good way), I believe popular react plugins such as `ReactCSSTransitionGroup` are not compatible.

Reference: https://facebook.github.io/react/docs/animation.html

**Comment by caseywebdev** [comment]
You're going to have to be more specific.

**Comment by bluejamesbond** [comment]
@caseywebdev updated

**Comment by caseywebdev** [comment]
[I worked up an example.](http://codepen.io/anon/pen/WrYQGR) ReactList is perfectly compatible with CSSTransitionGroup, you just need to leverage the `itemsRenderer` prop.

**Comment by bluejamesbond** [comment]
@caseywebdev Thank you!

**Comment by bluejamesbond** [comment]
@caseywebdev Is there a way to not animate `transitionAppear` on elements as you scroll down. Functionally speaking it seems to be correct, however from a UX aspect, transitioning on every scroll can be a bit much.
