### ISSUE TITLE
changes in items prop does not trigger rerender

### ISSUE THREAD

**Issue by trungpham** [orgsync/react-list#9]
https://github.com/orgsync/react-list/blob/master/react-list.js#L79
see the line above

since javascript uses reference pointer, it thinks the two arrays are identical because they are pointing to the same array.
to work around this, I have to clone the items to trick it into thinking that they are different. this is bad because it will lead to memory leak.
how about have another prop called version, which I can manually increment when I detect the items array has changed.

**Comment by caseywebdev** [comment]
You can pass your `version` prop in as the code stands right now. If it changes it will cause the `shouldComponentUpdate` to return `true`.

**Comment by trungpham** [comment]
cool. thanks.
