### ISSUE TITLE
Slow and difficult scroll in iOS Safari

### ISSUE THREAD

**Issue by vishalvijay** [orgsync/react-list#91]
Please have look at the videos

iOS 9.2.1 Safari/601.1 (With scrolling issue), in Firefox (Both iOS and Android) also it is **bit** laggy but not as like Safari
https://youtu.be/BLb2nCulft0

Chrome (Without scrolling issue, both Android and iOS it is fine)
https://youtu.be/04S5Nxb5Q1M

In safari it is very difficult and slow to scroll the list. I have integrated react-list multiple places, everywhere facing the same issue.

```
<div style={{overflow: 'auto', maxHeight: this.getListHeight(), height: this.getListHeight()}}>
  <ReactList itemRenderer={this.renderItem} length={this.props.products.length} type='uniform' initialIndex={this.state.index} />
</div>
```

**Comment by caseywebdev** [comment]
I'm not able to replicate this on the demo page (http://devblog.orgsync.com/react-list/). Does it scroll slow for you on that page?

**Comment by caseywebdev** [comment]
You might also try adding the `-webkit-overflow-scrolling: touch` style to your overflow div.

**Comment by Rob-ot** [comment]
@vishalvijay One other thing to check: make sure you aren't rendering the rows too often. In our case (and probably most others) we had to use shouldComponentUpdate to prevent the rows from being rendered every "frame" of scrolling.
