### ISSUE TITLE
Async request on scroll

### ISSUE THREAD

**Issue by moimael** [orgsync/react-list#92]
Hi,

I just found this component and it works great, good work !

I just have one question: 

How to fire an async request before (or after) the renderItem ? I need the index parameter in the request to be able to do async paged requests and I can't fire a flux action in a render method. Any idea ?

Thanks.

**Comment by caseywebdev** [comment]
I would recommend using something like [underscore's `_.debounce`](http://underscorejs.org/#debounce) to fire a method in the render call and update your state accordingly.

**Comment by moimael** [comment]
It seems that react-list do not rerender when my list of items changes. Since in your lib shouldComponentUpdate compare props and state and they don't change (the renderItem method is the same), it might be a bug ?

Here is my (simplified) code :

```
  renderItem(index, key) {
    _.debounce(PhotoActions.fetchPhotoList(index), 100);
    let photoList = [];
    if (this.props.photoList.length !== 0) {
      photoList = this.props.photoList[index];
    }
    return (
      <PhotoGrid key={key}
          items={photoList} onItemClick={this.handleOpenLightbox}
      />
    );
  }

render() {
            return (<ReactList
                itemRenderer={this.renderItem}
                length={10}
                useTranslate3d
                type='variable'
            />);
}
```

**Comment by caseywebdev** [comment]
See #36.

**Comment by moimael** [comment]
Ok it does solve my problem, thanks a lot for your quick help :) 

It does seem a little hackish though, can't you check if items changed directly in react-list ? And if that's not feasible, maybe a bit of documentation could help :)

Thanks !

**Comment by moimael** [comment]
I still get react errors when using debounce. It is completely forbidden to change state in render. But using renderItem method to get index does not leave me much choice.

**Comment by caseywebdev** [comment]
```js
class MyComponent extends Component {
loadStuff = _.debounce(() => {
  // load stuff...
}, 100);

renderItem(index, key) {
  item = myItems[index];
  if (!item) return this.loadStuff();
  return <div key={key}>{item}</div>;
}

render() {
  return <ReactList ... />;
}
}
```

I use this exact pattern in several places and it works great.
