### ISSUE TITLE
make item as props.children

### ISSUE THREAD

**Issue by warmhug** [orgsync/react-list#97]
Now, `itemRenderer` as a prop of ReactList, this is not flexible.
Because, some other component also need to operate each item very likely, but thus they can not do it.
So, maybe this format is better?
```html
<ReactList ...>
  <ReactListItem></ReactListItem>
  ...
</ReactList>
```

**Comment by caseywebdev** [comment]
I've found the current format to be extremely flexible. I see no reason for a change like this or even how it would work as you don't know how many or which items your're rendering at the time you instantiate the component.
